# ─── Stage 1: Dependencies ──────────────────────────────────────────────────
FROM node:25-alpine AS deps

RUN apk add --no-cache libc6-compat
WORKDIR /app

# Workspaces in package.json reference packages/* — we need the workspace
# package manifests present BEFORE `npm ci` so npm can wire them up. The
# actual source is copied in the build stage.
COPY package.json package-lock.json* ./
COPY packages/shared/package.json ./packages/shared/package.json
RUN npm ci

# ─── Stage 2: Build ─────────────────────────────────────────────────────────
FROM node:25-alpine AS build

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY package.json package-lock.json* ./
COPY packages/ ./packages/
COPY src/ ./src/
COPY public/ ./public/
COPY next.config.js tsconfig.json tailwind.config.js postcss.config.js ./

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

RUN npm run build

# ─── Stage 3: Runtime ───────────────────────────────────────────────────────
FROM node:25-alpine AS runtime

LABEL org.opencontainers.image.title="social-perks"
LABEL org.opencontainers.image.description="Social Perks — Turn Customers Into Your Marketing Team"
LABEL org.opencontainers.image.source="https://github.com/benzatkulak/social-perks"
LABEL org.opencontainers.image.vendor="Social Perks"

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Copy public assets
COPY --from=build /app/public ./public

# Copy standalone server and node_modules
COPY --from=build --chown=nextjs:nodejs /app/.next/standalone ./

# Copy static assets generated by Next.js
COPY --from=build --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=10s --start-period=15s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://localhost:3000/api/v1/health || exit 1

CMD ["node", "server.js"]
