// Hook landing pages — TikTok/Instagram bio link destinations.
// Mobile-first, single-CTA squeeze pages.

export type HookConversionType = "signup" | "newsletter" | "guide-download";

export interface Hook {
  slug: string;
  hook: string;
  promise: string;
  proofStat: string;
  socialPost: string;
  steps: string[];
  template: string;
  cta: string;
  conversionType: HookConversionType;
}

export const HOOKS: Hook[] = [
  {
    slug: "how-i-got-1000-instagram-followers-in-30-days",
    hook: "How I got 1,000 Instagram followers in 30 days",
    promise: "The exact 30-day content + engagement playbook I used. No bots. No paid ads.",
    proofStat: "1,000 followers in 30 days",
    socialPost: "30 days. 1K followers. No ads. Full playbook in my bio.",
    steps: [
      "Post 1 Reel every weekday at 7pm local time.",
      "Comment on 20 accounts in your niche every morning.",
      "Use 5 broad + 5 niche + 5 hyperlocal hashtags.",
      "Reply to every comment within 1 hour for the first 24 hours.",
      "Run a perk drop on day 14 to spike shares and saves.",
      "DM your top 10 commenters with a thank-you perk on day 21.",
    ],
    template:
      "DAILY CHECKLIST\n7:00am: Comment on 20 accounts (genuine, 2+ sentences).\n12:00pm: Reply to every DM.\n7:00pm: Post 1 Reel (hook in first 1.5s).\n9:00pm: Post 1 Story with a poll.\nWEEKLY: Run 1 perk drop. Tag your top 3 customers.",
    cta: "Get the full 30-day calendar",
    conversionType: "guide-download",
  },
  {
    slug: "the-5-second-google-review-script-that-works",
    hook: "The 5-second Google review script that actually works",
    promise: "The exact text-message script that gets a 64% reply rate.",
    proofStat: "64% reply rate from real customers",
    socialPost: "This 5-second script gets 64% of customers to leave a Google review. Steal it in my bio.",
    steps: [
      "Wait 2 hours after the purchase — not days.",
      "Text from a real person's number, not a 5-digit shortcode.",
      "Lead with their first name and what they bought.",
      "Drop the direct Google review link — no menu, no clicks.",
      "Offer a small perk on next visit as a thank-you.",
      "Never ask twice. One follow-up max, 3 days later.",
    ],
    template:
      "Hi {first_name}, it's {your_name} from {business}. Loved having you in today for {item}. If you have 10 seconds, would you drop us a quick Google review? Here's the direct link: {link}. Next time you're in, your {drink/side/add-on} is on me.",
    cta: "Get the script + perk follow-up",
    conversionType: "guide-download",
  },
  {
    slug: "why-your-instagram-engagement-dropped-and-how-to-fix-it",
    hook: "Why your Instagram engagement dropped (and how to fix it)",
    promise: "The 6 silent killers behind the 2025 engagement crash — and the 1-week recovery plan.",
    proofStat: "Engagement back up 3.2x in 7 days",
    socialPost: "Your IG engagement tanked because of THIS. Fix in my bio.",
    steps: [
      "Stop posting more than once per day — the algorithm punishes spam.",
      "Kill carousel posts longer than 5 slides. Drop-off is brutal.",
      "Add captions to every Reel — silent viewers don't convert.",
      "Move trending audio to the first 1.5 seconds, not the hook.",
      "Post when YOUR audience is online, not when 'experts' say.",
      "Reply to comments within 60 minutes for the first 2 hours.",
    ],
    template:
      "ENGAGEMENT AUDIT (do once a month)\n1. Pull last 30 posts. Sort by save rate.\n2. Note which 5 posts had 2x your average saves.\n3. Reverse-engineer the hook, format, and topic.\n4. Make 4 variations of each in the next 14 days.\n5. Kill any format that hasn't hit 1x your average saves in 30 days.",
    cta: "Get the recovery playbook",
    conversionType: "guide-download",
  },
  {
    slug: "the-tiktok-trick-that-fills-restaurant-tables",
    hook: "The TikTok trick that fills restaurant tables",
    promise: "The 90-second format that drove 400 walk-ins for a 30-seat restaurant.",
    proofStat: "400 walk-ins from 1 TikTok",
    socialPost: "This one TikTok filled my restaurant for 3 weeks. Format in my bio.",
    steps: [
      "Film from the kitchen pass at golden hour. No tripod, just hand-held.",
      "Open with the loudest sizzle of the night — sound, not visuals.",
      "Show one dish being plated in real time. No cuts.",
      "Caption: 'On the menu tonight at {your name}.' Nothing more.",
      "Pin a comment with your address + reservation link.",
      "Reply to every comment within 4 hours with a perk for first-timers.",
    ],
    template:
      "TIKTOK SHOT LIST (90 seconds)\n0-2s: Sizzle / open flame / pour close-up.\n2-15s: One full plating, real time, no cuts.\n15-20s: Plate hits the pass, server picks up.\n20-30s: Quick pan across the dining room.\nCaption: 'On the menu tonight at {name}. {Neighborhood}.'\nPinned comment: 'Address + book here: {link}'",
    cta: "Get the shot list + caption pack",
    conversionType: "guide-download",
  },
  {
    slug: "how-to-go-viral-on-tiktok-without-dancing",
    hook: "How to go viral on TikTok without dancing",
    promise: "The 4 'boring business' formats that consistently hit 500K+ views.",
    proofStat: "4 formats. 12 million views. Zero choreography.",
    socialPost: "Went viral on TikTok without ever showing my face. 4 formats in my bio.",
    steps: [
      "Format 1: 'How it's made' — show one process, hands only, 30 seconds.",
      "Format 2: 'POV: you walk into a {your business}' — first-person walk-through.",
      "Format 3: 'Things at my {business} that just make sense' — montage of details.",
      "Format 4: 'Day in the life' — but only show 3 moments, not 30.",
      "Hook in the first 1.5 seconds — text on screen + sound cue.",
      "Never end on a CTA. End on the most satisfying frame.",
    ],
    template:
      "FACELESS VIRAL TEMPLATE\nHook (0-1.5s): On-screen text question + sound cue.\nBody (1.5-25s): One process, hands only, real-time.\nPayoff (25-30s): The final result, held for 2 full seconds.\nCaption: 1 sentence + 3 hashtags max.\nSound: Trending audio at 30% volume under your real sound.",
    cta: "Get all 4 format templates",
    conversionType: "guide-download",
  },
  {
    slug: "the-instagram-bio-that-doubled-my-bookings",
    hook: "The Instagram bio that doubled my bookings",
    promise: "The 4-line bio formula and the exact link-in-bio stack that converts.",
    proofStat: "Bookings up 2.1x in 6 weeks",
    socialPost: "Changed 4 lines in my IG bio. Bookings doubled. Formula in my bio.",
    steps: [
      "Line 1: What you do + who it's for (no adjectives).",
      "Line 2: A proof number with a unit ('500 happy clients in Austin').",
      "Line 3: One reason to follow (free thing, schedule, or perk).",
      "Line 4: One emoji + CTA verb + the link.",
      "Use a single link — multi-link pages cut clicks by 40%.",
      "Update the bio every 30 days to match what's actually working.",
    ],
    template:
      "THE 4-LINE BIO\nLine 1: {What you do} for {who}.\nLine 2: {Proof number} since {year}.\nLine 3: Free {thing} every {cadence}.\nLine 4: Book / Shop / Join below.\n\nEXAMPLE\nHair color for redheads.\n900+ heads since 2019.\nFree color quiz every Friday.\nBook below.",
    cta: "Get the bio formula + link stack",
    conversionType: "guide-download",
  },
  {
    slug: "3-mistakes-killing-your-google-business-profile",
    hook: "3 mistakes killing your Google Business Profile",
    promise: "The 3 silent ranking killers — and the 15-minute fix for each.",
    proofStat: "From rank 12 to rank 2 in 21 days",
    socialPost: "Your Google Business Profile is invisible because of these 3 things. Fix in my bio.",
    steps: [
      "Mistake 1: No new photos in 30+ days. Add 5 weekly.",
      "Mistake 2: Hours don't match your door. Update for every holiday.",
      "Mistake 3: Ignoring 4-star reviews. Reply to every single one.",
      "Add 1 Google Post per week — not per month.",
      "Use your primary category exactly. No 'creative' edits.",
      "Add a Q&A — seed it with the 5 questions customers actually ask.",
    ],
    template:
      "WEEKLY GBP CHECKLIST (15 min)\nMonday: Upload 5 fresh photos.\nTuesday: Reply to every review from last week.\nWednesday: Post 1 Google Post with a perk.\nThursday: Check hours for the next 7 days.\nFriday: Answer 1 Q&A question.",
    cta: "Get the full GBP fix list",
    conversionType: "guide-download",
  },
  {
    slug: "how-i-got-127-reviews-in-30-days",
    hook: "How I got 127 reviews in 30 days",
    promise: "The exact ask-script, timing, and perk that turned every customer into a reviewer.",
    proofStat: "127 reviews. 4.9 average. 30 days.",
    socialPost: "127 Google reviews in 30 days. No bots. Script + perk in my bio.",
    steps: [
      "Print the direct review QR code at the register.",
      "Train every employee to point at it — not say a word about it.",
      "Text the customer 2 hours after they leave, never sooner.",
      "Offer one small perk per review, redeemable next visit only.",
      "Reply to every review within 24 hours — even 5-stars.",
      "Run a leaderboard for staff: most reviews-per-shift wins.",
    ],
    template:
      "THE 127 SYSTEM\nIn-store: QR code at register, eye level. Staff points, doesn't speak.\n2 hours after: 'Hi {name}, it's {your_name}. If you'd drop us a quick review, your next {item} is on us. Link: {url}'\nReview reply (5-star): 'Thanks {name} — see you for that {item} on us soon.'\nReview reply (4-star): 'Thanks {name}. What would've made it 5? DM me — your next visit is on me.'",
    cta: "Get the 127-review playbook",
    conversionType: "guide-download",
  },
  {
    slug: "the-customer-perk-that-triples-social-shares",
    hook: "The customer perk that triples social shares",
    promise: "The perk structure that turned 8% of customers into active promoters.",
    proofStat: "Social shares up 3.1x in 60 days",
    socialPost: "One perk. 3x the shares. Structure in my bio.",
    steps: [
      "Make the perk redeemable only after the share — not before.",
      "Set the threshold at 1 post or 1 Story tag. Don't ask for more.",
      "Make the reward feel premium — a free upgrade, not a 10% discount.",
      "Require the @tag to be on the actual post, not just the caption.",
      "Auto-DM a thank-you with a second perk for the next 14 days.",
      "Feature the top 3 sharers on your own feed every month.",
    ],
    template:
      "THE 3X PERK STRUCTURE\nAsk: Tag @{your_handle} in 1 post or Story.\nReward: Free {premium item}, not a discount.\nWindow: Redeem within 14 days.\nFollow-up DM: 'Thanks {name} — your {item} is waiting. Bring a friend, both get one.'\nMonthly: Post a 'Top 3 customers this month' carousel.",
    cta: "Get the perk structure + DM scripts",
    conversionType: "signup",
  },
  {
    slug: "the-influencer-dm-template-that-actually-works",
    hook: "The influencer DM template that actually works",
    promise: "The 4-line DM that gets a 38% reply rate from creators with 10K-100K followers.",
    proofStat: "38% reply rate. 12% close rate.",
    socialPost: "This DM gets creators to reply. Template in my bio.",
    steps: [
      "Open with a specific post — not 'love your content'.",
      "Mention one detail that proves you watched, not skimmed.",
      "State the offer in one sentence. No vague 'collab'.",
      "Give a clear yes/no question, not a 5-paragraph pitch.",
      "Send between Tuesday and Thursday, 7-9pm local.",
      "Never follow up more than once. Move on.",
    ],
    template:
      "THE 4-LINE DM\nLine 1: 'Hey {name}, your {specific post} on {topic} — the part about {detail} was the best take I've seen this year.'\nLine 2: 'I run {business}, a {one-line description} in {city}.'\nLine 3: 'I'd love to send you {specific perk worth $X} in exchange for one Reel or 3 Stories. No script, your voice.'\nLine 4: 'Open to it? Yes or no is totally fine.'",
    cta: "Get the DM + 3 follow-up scripts",
    conversionType: "guide-download",
  },
  {
    slug: "stop-doing-this-on-instagram-now",
    hook: "Stop doing this on Instagram. Now.",
    promise: "The 7 habits the 2025 algorithm punishes — and what to do instead.",
    proofStat: "Reach back up 4x in 14 days",
    socialPost: "If you do these 7 things on IG, you'll never grow. List in my bio.",
    steps: [
      "Stop posting links in captions. Move them to a Story sticker.",
      "Stop using more than 8 hashtags. Diminishing returns past 8.",
      "Stop reposting other people's Reels. Originality score matters now.",
      "Stop deleting underperforming posts. It tanks the whole feed.",
      "Stop using #followforfollow or any banned tag. Check the list monthly.",
      "Stop posting at 'optimal times.' Post when YOUR audience is on.",
      "Stop ignoring DMs. Reply rate is now a ranking signal.",
    ],
    template:
      "THE 'STOP' AUDIT (do once a week)\n1. Open last 7 posts.\n2. Count hashtags. If >8 on any, edit down.\n3. Check for any link in caption. Remove and move to Story.\n4. Look at DM inbox. Reply to every one from the last 7 days.\n5. Open Insights → Audience → 'Most Active Times'. Post at the top 2 windows next week.",
    cta: "Get the full 'stop' list",
    conversionType: "newsletter",
  },
  {
    slug: "how-to-get-influencers-to-promote-you-for-free",
    hook: "How to get influencers to promote you for free",
    promise: "The trade structure that gets 10K-50K creators to post without a single dollar changing hands.",
    proofStat: "27 free posts. $0 spent.",
    socialPost: "Got 27 influencers to post about me for $0. System in my bio.",
    steps: [
      "Target creators with 5K-25K followers — they need content more than cash.",
      "Lead with the experience, not the product. 'Come in, on us.'",
      "Bundle the perk: include a +1 so they bring a content partner.",
      "Make the trade explicit: 1 Reel + 3 Stories within 14 days.",
      "Send a follow-up perk for repeat posts in months 2 and 3.",
      "Track every post in a spreadsheet. Re-engage your top 3 quarterly.",
    ],
    template:
      "THE FREE-PROMO OFFER\nWho: Creators with 5K-25K followers in your zip code.\nOffer: '$X experience for you + 1 guest, on us.'\nAsk: '1 Reel + 3 Stories tagging us, within 14 days.'\nFollow-up: Day 30, send a 'come back' perk worth 50% of the first.\nQuarterly: Re-invite your top 3 performers with a bigger perk.",
    cta: "Get the outreach + tracking sheet",
    conversionType: "signup",
  },
  {
    slug: "the-hashtag-formula-that-grew-my-account-by-10k",
    hook: "The hashtag formula that grew my account by 10K",
    promise: "The 5+5+5 hashtag stack that 4x'd my reach in 90 days.",
    proofStat: "10,247 followers in 90 days from hashtags alone",
    socialPost: "Stole this hashtag formula. Grew 10K followers. In my bio.",
    steps: [
      "5 broad tags (1M+ posts) — for discovery only.",
      "5 niche tags (50K-500K posts) — your actual home.",
      "5 hyperlocal tags (under 10K posts) — where you win.",
      "Rotate the broad 5 every week to avoid 'shadowban' patterns.",
      "Never repeat the exact same 15 across 2 posts in a row.",
      "Track top-performer tags monthly. Keep what works, kill what doesn't.",
    ],
    template:
      "THE 5+5+5 STACK\nBROAD (1M+): #smallbusiness #localbusiness #shopsmall #entrepreneur #womeninbusiness\nNICHE (50K-500K): #{yourcity}eats #{yourindustry}life #{specific niche tag} #independentbusiness #buylocal\nHYPERLOCAL (<10K): #{yourneighborhood} #{yourzipcode} #{nearestlandmark} #{citynightlife} #{your specific category in your city}",
    cta: "Get the swipe file of 200+ tags",
    conversionType: "guide-download",
  },
  {
    slug: "why-90-percent-of-small-businesses-fail-at-tiktok",
    hook: "Why 90% of small businesses fail at TikTok",
    promise: "The 5 fatal mistakes — and the simple shift that fixes all of them.",
    proofStat: "From 0 to 50K followers after 1 shift",
    socialPost: "90% of small businesses are doing TikTok wrong. Here's the 1 shift in my bio.",
    steps: [
      "Mistake 1: Treating it like Instagram. Different audience, different pace.",
      "Mistake 2: No face on camera, ever. Faceless works, but you need ONE recurring voice.",
      "Mistake 3: 60-second videos. The sweet spot is 19-26 seconds.",
      "Mistake 4: No trending audio. You don't have to dance, but use the sound.",
      "Mistake 5: One post per week. Three per week minimum.",
      "The fix: pick one format. Post it 3x a week. For 90 days. No exceptions.",
    ],
    template:
      "THE 90-DAY TIKTOK PLAN\nWeek 1: Pick ONE format (process, POV, montage, talking head).\nWeek 1-12: Post that format 3x/week. 19-26 seconds each.\nWeek 1-12: Use trending audio at low volume under your real audio.\nWeek 6 check-in: Pull top 3 videos. Reverse-engineer the hook. Double down.\nWeek 12: Audit. Keep the format if avg views > 1,500. Switch if not.",
    cta: "Get the 90-day plan",
    conversionType: "guide-download",
  },
  {
    slug: "the-customer-text-that-gets-90-percent-replies",
    hook: "The customer text that gets 90% replies",
    promise: "The exact SMS that turns one-time buyers into repeat customers.",
    proofStat: "92% reply rate. 41% rebook rate.",
    socialPost: "92% of customers reply to this text. Steal it in my bio.",
    steps: [
      "Send it 48 hours after the visit — not the next day.",
      "Use the customer's first name and the exact thing they bought.",
      "Ask one question only — never two, never a paragraph.",
      "Always offer a perk for the answer, but never lead with it.",
      "Send between 11am and 2pm — outside that window, reply rate halves.",
      "Never use a 5-digit shortcode. Real number, real human.",
    ],
    template:
      "THE 90% TEXT\n'Hey {first_name}, it's {your_name} from {business}. Quick one — how was the {item} from Tuesday? On a scale of 1-10. (No wrong answer — and your next one's on us either way.)'",
    cta: "Get the SMS + 5 follow-up scripts",
    conversionType: "guide-download",
  },
  {
    slug: "how-to-respond-to-bad-yelp-reviews-the-right-way",
    hook: "How to respond to bad Yelp reviews the right way",
    promise: "The 4-line reply template that turns 1-stars into apologies — and sometimes 5-stars.",
    proofStat: "37% of 1-star reviewers updated to 4+ after this reply",
    socialPost: "This 4-line reply turned a 1-star Yelp into a 5-star. Template in my bio.",
    steps: [
      "Reply within 24 hours, max. Faster = better.",
      "Use their first name. Don't open with 'Dear customer.'",
      "Acknowledge the specific complaint — not 'we're sorry you had a bad experience.'",
      "Offer a real fix, in public. Not 'DM us for resolution.'",
      "Never argue, even when they're wrong. Never.",
      "Sign your real first name and role. Not 'The Management Team.'",
    ],
    template:
      "THE 4-LINE REPLY\nLine 1: '{Name}, I'm sorry — and you're right.'\nLine 2: '{Specific issue} should never have happened. Here's what I'm doing about it: {one concrete change}.'\nLine 3: 'Your next visit is on me — just ask for {your name} and bring this reply.'\nLine 4: '— {Your first name}, owner.'",
    cta: "Get the reply templates for every star rating",
    conversionType: "guide-download",
  },
  {
    slug: "the-loyalty-program-that-makes-customers-tag-you",
    hook: "The loyalty program that makes customers tag you",
    promise: "The 'tag-to-earn' structure that turned 14% of customers into weekly promoters.",
    proofStat: "14% of customers post weekly. For free.",
    socialPost: "My loyalty program runs itself — customers tag me every week. Structure in my bio.",
    steps: [
      "Replace points-per-dollar with points-per-tag.",
      "Set the redemption threshold low — 5 tags = a real perk.",
      "Reward Story tags AND post tags, but post tags = 3x the points.",
      "Send a weekly leaderboard text to your top 20 members.",
      "Auto-feature the top tagger every month on your own feed.",
      "Re-engage lapsed members at 30 days with a 'bonus week' offer.",
    ],
    template:
      "TAG-TO-EARN STRUCTURE\nEarn: 1 Story tag = 1 point. 1 post tag = 3 points.\nRedeem: 5 points = free {standard item}. 15 points = free {premium item}. 30 points = VIP perk.\nLeaderboard text (every Monday): 'You're #{rank} this week, {name}. {Top tagger's name} is in the lead with {x} tags.'\nMonthly feature: 'Top customer this month: @{handle}' on your own feed.",
    cta: "Get the full program blueprint",
    conversionType: "signup",
  },
  {
    slug: "the-free-tool-that-finds-influencers-in-your-niche",
    hook: "The free tool that finds influencers in your niche",
    promise: "How to surface 50 perfect-fit creators in your city — without paying for a platform.",
    proofStat: "50 creators in 1 hour. $0.",
    socialPost: "Found 50 perfect influencers in my city for $0. Tool in my bio.",
    steps: [
      "Start with the hyperlocal hashtag for your neighborhood.",
      "Open the top 30 posts of the week, not the all-time top.",
      "Filter for creators with 2K-25K followers and 4%+ engagement.",
      "Check their last 9 posts — at least 6 must be in your niche.",
      "Drop them in a sheet with: handle, followers, last-post date, why-fit.",
      "Send 5 DMs a day, never more. Quality > volume.",
    ],
    template:
      "THE FREE-FIND SPREADSHEET\nColumns: Handle | Followers | Eng % | Niche match (1-5) | Last post date | DM sent (date) | Reply (Y/N) | Posted (Y/N) | Notes\nDaily target: Add 10 creators, send 5 DMs, reply to 100% of incoming.\nWeekly target: 35 DMs sent, 12+ replies, 4+ confirmed posts.",
    cta: "Get the spreadsheet + DM scripts",
    conversionType: "signup",
  },
  {
    slug: "how-i-doubled-my-bookings-without-paid-ads",
    hook: "How I doubled my bookings without paid ads",
    promise: "The 5-channel organic stack that replaced my $4K/month ad spend.",
    proofStat: "Bookings 2.4x. Ad spend $0.",
    socialPost: "Doubled bookings. Killed all paid ads. 5-channel stack in my bio.",
    steps: [
      "Channel 1: Google Business Profile — 5 photos, 1 post, 5 review replies per week.",
      "Channel 2: Instagram Reels — 3 per week, same hook format.",
      "Channel 3: SMS to past customers — 1 perk drop per month.",
      "Channel 4: 1 micro-influencer trade per week (free product, 1 Reel ask).",
      "Channel 5: Customer tag-to-earn program — 14% participation target.",
      "Track only one metric per channel. Drop anything that doesn't move it in 30 days.",
    ],
    template:
      "THE 5-CHANNEL WEEKLY CHECKLIST\nMonday: 5 GBP photos + 1 post.\nTuesday: 1 Reel.\nWednesday: SMS perk drop to past 90-day customers.\nThursday: 1 Reel. 1 micro-influencer DM.\nFriday: Reply to all reviews from the week. 1 Reel.\nSunday: 10-min audit — kill any channel under target.",
    cta: "Get the full 5-channel system",
    conversionType: "signup",
  },
  {
    slug: "the-instagram-story-trick-restaurants-don-t-know",
    hook: "The Instagram Story trick restaurants don't know",
    promise: "The 3-frame Story format that fills tables for the same night.",
    proofStat: "From 12 to 47 covers — same night",
    socialPost: "This 3-frame IG Story fills tables for the same night. In my bio.",
    steps: [
      "Frame 1 (sizzle): Close-up of one dish, 5 seconds, real sound.",
      "Frame 2 (proof): A countdown sticker — 'tables open at 6, 8, 9pm.'",
      "Frame 3 (action): A link sticker straight to the reservation page.",
      "Post between 11:30am and 1:00pm for that night's covers.",
      "Add a poll on frame 2 ('Coming tonight?') — engagement boosts reach.",
      "Re-share the best frame from a happy guest to your feed by 10pm.",
    ],
    template:
      "THE 3-FRAME STORY\nFrame 1: 5-sec close-up of tonight's special. Real kitchen sound.\nFrame 2: 'Tables open: 6pm / 8pm / 9pm' + countdown sticker + poll ('Coming tonight?').\nFrame 3: Hero shot of the dining room + link sticker to reservation.\nPost time: 11:30am-1:00pm same day.\nFollow-up: Reshare a customer's tagged story by 10pm.",
    cta: "Get the Story templates",
    conversionType: "guide-download",
  },
  {
    slug: "why-no-one-is-saving-your-instagram-posts",
    hook: "Why no one is saving your Instagram posts",
    promise: "The 4 'save triggers' that the 2025 algorithm rewards above everything else.",
    proofStat: "Saves up 6x in 30 days",
    socialPost: "No one saves your posts because of this. Fix in my bio.",
    steps: [
      "Save trigger 1: Lists. Numbered lists save 3x more than prose.",
      "Save trigger 2: Templates the reader will need later (swipe-files).",
      "Save trigger 3: Step-by-step screenshots with arrows + circles.",
      "Save trigger 4: 'Don't do this' posts. Threat-of-loss > promise-of-gain.",
      "Put the save-worthy content on slide 3 of a carousel, not slide 1.",
      "End every save-trigger post with: 'Save this for {specific future moment}.'",
    ],
    template:
      "THE SAVE-TRIGGER FORMULA\nSlide 1: A hook + a number ('7 things I wish I knew before...').\nSlide 2: The setup ('Most people do X. Here's why it fails.').\nSlide 3: The list / template / steps — the actual save-worthy content.\nSlides 4-7: Expand on each step with examples.\nFinal slide: 'Save this for {specific future moment, e.g., your next launch}.'",
    cta: "Get the save-trigger swipe file",
    conversionType: "newsletter",
  },
  {
    slug: "how-to-write-a-tiktok-bio-that-converts",
    hook: "How to write a TikTok bio that converts",
    promise: "The 3-line bio formula that took my profile-to-follow rate from 4% to 27%.",
    proofStat: "Profile-to-follow rate: 4% → 27%",
    socialPost: "Changed 3 lines in my TikTok bio. Follows tripled. Formula in my bio.",
    steps: [
      "Line 1: One thing you make, for one type of person.",
      "Line 2: One number that proves it (followers, customers, years).",
      "Line 3: One emoji + one CTA verb + the link.",
      "No adjectives. No 'passionate.' No emoji-only lines.",
      "Match your username to your category, not your brand.",
      "Update the bio every Sunday for the week ahead.",
    ],
    template:
      "THE 3-LINE TIKTOK BIO\nLine 1: {Specific thing you make} for {specific audience}.\nLine 2: {Number} + {unit} since {year}.\nLine 3: {emoji} {Verb} below → {link}.\n\nEXAMPLE\nWine-bar pop-ups in Brooklyn.\n9,000 covers since 2023.\n🍷 Book this week's seat below ↓",
    cta: "Get the bio formula + 25 examples",
    conversionType: "guide-download",
  },
  {
    slug: "the-content-batching-system-that-saves-10-hours-a-week",
    hook: "The content batching system that saves 10 hours a week",
    promise: "How to film, edit, and schedule a full month of content in one afternoon.",
    proofStat: "30 posts in 1 afternoon. 10 hrs/week back.",
    socialPost: "Batched a month of content in 4 hours. System in my bio.",
    steps: [
      "Pick 1 location, 2 outfit changes, 1 lighting setup. That's the whole shoot.",
      "Film 12 Reels back-to-back in 90 minutes. No edits between takes.",
      "Use the same hook structure for all 12. Just change the topic.",
      "Edit in one 90-minute block. No second-guessing on takes.",
      "Caption all 12 in a single 30-minute writing sprint, voice-to-text.",
      "Schedule with one tool. Never post manually again.",
    ],
    template:
      "BATCHING DAY (4 hours total)\n0:00-0:30: Outline 12 hooks + topics on paper.\n0:30-2:00: Film 12 Reels in 2 outfits.\n2:00-3:30: Edit all 12 (5-7 min each).\n3:30-4:00: Caption all 12 + schedule.\nResult: 4 weeks of content in 1 afternoon.",
    cta: "Get the batching template + tool stack",
    conversionType: "guide-download",
  },
  {
    slug: "the-3-emails-that-bring-customers-back",
    hook: "The 3 emails that bring customers back",
    promise: "The exact subject lines, body copy, and timing for a 23% reactivation rate.",
    proofStat: "23% of dormant customers came back",
    socialPost: "These 3 emails reactivated 23% of my dormant customers. In my bio.",
    steps: [
      "Email 1 (day 30): 'We saved your spot' — soft check-in, no offer.",
      "Email 2 (day 45): 'On the house' — one specific perk, 7-day expiry.",
      "Email 3 (day 60): 'Last chance' — same perk, urgency-only language.",
      "Send between 8:30am and 9:30am Tuesday or Thursday.",
      "Plain-text email beats designed templates 2:1 for reactivation.",
      "Always sign with a real name and reply-to address.",
    ],
    template:
      "EMAIL 1 — Day 30\nSubject: We saved your spot, {name}.\nBody: 'Hey {name}, it's {your_name} from {business}. Noticed it's been a minute since we saw you. No pitch — just wanted to say your favorite {item} is still on the menu. — {Your name}'\n\nEMAIL 2 — Day 45\nSubject: On the house.\nBody: 'Hey {name}, {your name} again. Come in this week and your {specific item} is on me. No code, just say my name. Expires Sunday. — {Your name}'\n\nEMAIL 3 — Day 60\nSubject: Last call.\nBody: 'Hey {name}, the {item} offer expires tomorrow night. After that, I'll stop bugging you. — {Your name}'",
    cta: "Get all 3 emails + send-time guide",
    conversionType: "guide-download",
  },
  {
    slug: "how-to-turn-1-happy-customer-into-50-instagram-posts",
    hook: "How to turn 1 happy customer into 50 Instagram posts",
    promise: "The repost engine that turns one delighted customer into a month of content.",
    proofStat: "1 customer → 50 posts of content",
    socialPost: "Turned ONE happy customer into 50 IG posts. System in my bio.",
    steps: [
      "Capture: ask permission to film a 60-second testimonial in-store.",
      "Cut: chop the 60 seconds into 10 short-form Reels (6 seconds each).",
      "Quote: pull 5 single-line quotes for static carousel slides.",
      "Behind-the-scenes: 5 Stories of the visit, lit cinematically.",
      "Tag-back: re-share every Story the customer posts to your own feed.",
      "Anniversary: post a 'one year ago today' carousel on their visit-aversary.",
    ],
    template:
      "1-CUSTOMER → 50-POST BREAKDOWN\n10 short Reels (testimonial cuts)\n5 quote carousels (5 slides each = 25 graphics)\n5 BTS Stories (highlighted to your profile)\n5 customer reshares (from their tagged Stories)\n5 'thank you' Reels (your own POV)\n+ 20 organic mentions across captions, replies, and reposts\n= 50+ pieces from a single visit.",
    cta: "Get the 50-post breakdown + shot list",
    conversionType: "guide-download",
  },
];
