export type Difficulty = "Beginner" | "Intermediate";

export interface Step {
  title: string;
  body: string;
  tip?: string;
  mistake?: string;
}

export interface Faq {
  q: string;
  a: string;
}

export interface Guide {
  slug: string;
  title: string;
  h1: string;
  category: string;
  description: string;
  timeMinutes: number;
  difficulty: Difficulty;
  learn: string[];
  prerequisites: string[];
  intro: string;
  steps: Step[];
  faqs: Faq[];
  nextCta: { heading: string; body: string; href: string; label: string };
}

export const CATEGORIES = [
  "Getting reviews",
  "Social media setup",
  "Content creation",
  "Customer acquisition",
  "Analytics & growth",
] as const;

const baseCta = {
  heading: "Let customers do the marketing",
  body: "Social Perks turns happy customers into a marketing team. Free 14-day trial. No card required.",
  href: "/ai",
  label: "Start free",
};

function mk(
  slug: string,
  category: string,
  title: string,
  h1: string,
  description: string,
  timeMinutes: number,
  difficulty: Difficulty,
  learn: string[],
  prerequisites: string[],
  intro: string,
  steps: Step[],
  faqs: Faq[],
): Guide {
  return {
    slug,
    title,
    h1,
    category,
    description,
    timeMinutes,
    difficulty,
    learn,
    prerequisites,
    intro,
    steps,
    faqs,
    nextCta: baseCta,
  };
}

// ---------- GETTING REVIEWS ----------
const REVIEWS: Guide[] = [
  mk(
    "how-to-get-more-google-reviews-fast",
    "Getting reviews",
    "How to get more Google reviews fast (2026 playbook)",
    "How to get more Google reviews fast",
    "A step-by-step playbook for collecting dozens of authentic Google reviews in 30 days without breaking Google's policies.",
    8,
    "Beginner",
    [
      "Why Google reviews drive 70% of local search rankings",
      "How to build a one-tap review link",
      "Three proven ask-templates with 40%+ conversion",
      "How to recover when a customer forgets",
    ],
    [
      "A claimed Google Business Profile",
      "A way to text or email customers (phone, POS, or email tool)",
      "About 30 minutes of one-time setup",
    ],
    "Google reviews are the single highest-leverage marketing asset a local business owns. They drive local pack rankings, click-through from the SERP, and conversion on your profile. The good news: most owners are leaving 80%+ of reviews on the table simply because they never ask. This guide walks through the exact system high-performing local businesses use to triple their review count in 30 days.",
    [
      {
        title: "Generate your short review link",
        body: "Sign in to your Google Business Profile, click 'Read reviews', then 'Get more reviews'. Google gives you a short URL like g.page/r/XXXX/review. Copy it. This is the only link you'll ever share — it opens the 5-star write-a-review screen with one tap.",
        tip: "Shorten it again with a branded vanity URL like yourshop.com/review using a 301 redirect.",
        mistake: "Sending people to your full business profile. Most won't find the review button and bounce.",
      },
      {
        title: "Pick the moment of peak happiness",
        body: "Ask within 1–4 hours of a great experience — not days later. For services, ask at checkout. For products, ask after first use. For restaurants, hand the request with the check. Latency kills response rates.",
        tip: "Set a POS automation that triggers a review SMS exactly 2 hours after the payment.",
        mistake: "Mass-blasting your whole list. Google flags spikes and may filter reviews.",
      },
      {
        title: "Write a 2-sentence ask script",
        body: "Keep it short. 'Hey [Name] — thanks for stopping by today. If you have 30 seconds, a quick Google review really helps a small shop like us: [link].' Personal, specific, low-effort. Test SMS vs email — SMS typically converts 3–5x higher.",
        tip: "Send from a person's name and number, not 'Marketing Team'.",
      },
      {
        title: "Make it absurdly easy",
        body: "One tap. The link should open Google directly into the star-selection screen. Don't send a PDF, don't ask for a screenshot, don't link to a landing page first.",
        mistake: "Asking customers to 'find us on Google and leave a review'. Conversion drops to under 5%.",
      },
      {
        title: "Follow up exactly once",
        body: "If they haven't reviewed within 4 days, send one polite nudge. After that, stop. Aggressive follow-ups generate negative reviews and unsubscribes.",
      },
      {
        title: "Respond to every single review within 24 hours",
        body: "Thank positives by name. For negatives, acknowledge, apologize, and offer to make it right offline. Google's algorithm rewards profiles with high response rates.",
        tip: "Use a 3-sentence template: thank, specific detail, invite back.",
      },
      {
        title: "Build review-asking into your workflow forever",
        body: "Reviews aren't a campaign — they're a habit. Bake the ask into checkout, order completion, and follow-up email sequences. Aim for one ask per transaction, forever.",
      },
    ],
    [
      { q: "Can I offer a discount for a review?", a: "No. Google explicitly prohibits incentivized reviews. You can offer a perk for the action of leaving feedback (not a specific star rating), but the safest play is a no-strings-attached ask." },
      { q: "How many reviews do I need to rank?", a: "There's no magic number, but 30+ recent reviews with a 4.5+ average is the local-pack sweet spot in most categories." },
      { q: "Should I ask unhappy customers?", a: "Ask everyone equally. Filtering only happy customers (review gating) violates Google's policy and is detectable." },
      { q: "How fast can I realistically see results?", a: "Most businesses double their review count in 30 days with daily asks. Visible ranking lifts typically come in 60–90 days." },
      { q: "What if a customer leaves a review on the wrong platform?", a: "Thank them, then send the Google link with a one-line note: 'Would you mind dropping a quick one on Google too? It helps us a lot.'" },
    ],
  ),
  mk(
    "how-to-respond-to-negative-reviews",
    "Getting reviews",
    "How to respond to negative reviews (without making it worse)",
    "How to respond to negative reviews",
    "Templates and a calm framework for turning angry one-star reviews into trust-building moments — without lawyers or drama.",
    7,
    "Beginner",
    [
      "The 24-hour rule that prevents 90% of mistakes",
      "A 4-part response framework (LEAP)",
      "When to take it offline vs. answer publicly",
      "How to flag fake or policy-violating reviews",
    ],
    [
      "Owner or manager access to the review platform",
      "A cool head — or 24 hours of distance",
    ],
    "A negative review feels like a personal attack. It isn't. It's a public moment where future customers watch you handle conflict. Done well, a one-star response can convert more browsers than a five-star review. Done poorly, it can sink a business. Here's the script the best operators use.",
    [
      {
        title: "Wait 24 hours before you type anything",
        body: "Never respond emotionally. The single most expensive marketing mistakes come from rage-typed replies. Read the review, sleep on it, then respond the next morning when you can be generous.",
        mistake: "Replying within minutes with a defensive tone. Future customers will read it forever.",
      },
      {
        title: "Use the LEAP framework",
        body: "Listen (restate their concern), Empathize (acknowledge the feeling), Apologize (own your part), Propose (offer next steps). Four short paragraphs, max.",
        tip: "Start with 'Thank you for the feedback' — never 'I'm sorry you feel that way'.",
      },
      {
        title: "Reply publicly, resolve privately",
        body: "Your public reply is for the audience of future customers. Two to four sentences max. Then move to email, phone, or DM for the actual resolution.",
      },
      {
        title: "Name the specific issue without arguing facts",
        body: "Don't dispute their version of events in public, even if they're wrong. 'I can see how that experience would be frustrating' is universally true and de-escalates instantly.",
        mistake: "Calling the customer a liar. You always lose this fight in public.",
      },
      {
        title: "Offer a concrete fix",
        body: "'I'd like to make this right — please email me at owner@shop.com.' Specific person, specific contact, specific offer (refund, redo, gift card).",
      },
      {
        title: "Flag fake or policy-violating reviews",
        body: "If the reviewer was never a customer, posted profanity, or named competitors, flag it through the platform (Google: three dots → Flag as inappropriate). Provide context if the platform asks.",
        tip: "Keep order records and timestamps so you can prove a fake review wasn't a real customer.",
      },
      {
        title: "Follow up after resolution and ask for an update",
        body: "When the issue is fixed, politely ask if they'd consider updating the review. Many will. Never demand it.",
      },
    ],
    [
      { q: "Should I respond to every negative review?", a: "Yes. Silence reads as guilt. Even a 2-sentence acknowledgement is better than nothing." },
      { q: "What if the review is completely false?", a: "Reply factually and calmly ('Our records show no order under this name on that date — please reach out so we can help'), then flag the review." },
      { q: "Can I sue for defamation?", a: "Rarely worth it. Public lawsuits backfire. Talk to a lawyer only if there's clear, provable, damaging falsehood." },
      { q: "Should I offer a refund publicly?", a: "Never. Offer privately. Public refunds attract bad-faith reviewers." },
      { q: "How do I prevent negative reviews in the first place?", a: "Build a fast complaint channel before checkout — make it easier to complain to you than to Google." },
    ],
  ),
  mk(
    "how-to-ask-customers-for-yelp-reviews",
    "Getting reviews",
    "How to ask customers for Yelp reviews (without getting filtered)",
    "How to ask customers for Yelp reviews",
    "Yelp's review filter is brutal. Here's how to legitimately grow Yelp reviews without triggering the algorithm.",
    7,
    "Beginner",
    [
      "Why Yelp filters 25% of new reviews",
      "What you can and cannot say (per Yelp's policy)",
      "Three soft-touch ask techniques",
      "How to surface filtered reviews",
    ],
    [
      "A claimed Yelp business page",
      "An email list or post-visit follow-up system",
    ],
    "Yelp openly discourages businesses from soliciting reviews and aggressively filters anything that looks fishy. But you absolutely can grow reviews — you just have to do it indirectly. Here's the legal, durable playbook.",
    [
      {
        title: "Claim and complete your Yelp page",
        body: "Add hours, photos, menu, services, and an owner bio. Yelp's filter trusts complete profiles more.",
      },
      {
        title: "Use 'Find us on Yelp' — not 'Review us on Yelp'",
        body: "Yelp's policy bans direct review asks. Instead, point people to your page. Once they're there, the call-to-review is Yelp's job, not yours.",
        mistake: "Putting 'Leave us a Yelp review' on receipts. Reviews that come from this often get filtered.",
      },
      {
        title: "Add a Yelp badge to your website and email signature",
        body: "Yelp provides embeddable badges that link to your page. Organic clickthroughs convert better and get filtered less.",
      },
      {
        title: "Mention Yelp in conversation, not in writing",
        body: "Train staff to casually say 'we love hearing from people on Yelp'. Spoken asks don't leave a paper trail and don't trigger filters.",
      },
      {
        title: "Reward Yelp Elite users (legally)",
        body: "Elite reviewers' reviews almost never get filtered. Host Elite events, offer them a tasting menu, treat them like critics — without asking for specific star ratings.",
        tip: "Yelp hosts free Elite events that you can sponsor — a great low-cost local visibility play.",
      },
      {
        title: "Respond to every review publicly",
        body: "A 2-sentence thank-you on positives, a calm LEAP response on negatives. Yelp boosts engaged businesses.",
      },
      {
        title: "Monitor your filter rate quarterly",
        body: "Click 'Not currently recommended reviews' below your review count. If filter rate exceeds 30%, you're being too aggressive — pull back.",
      },
    ],
    [
      { q: "Why does Yelp filter so many reviews?", a: "Their algorithm penalizes reviewers with thin profiles, new accounts, and patterns that look solicited (clusters of reviews after a visit, similar phrasing)." },
      { q: "Can I incentivize Yelp reviews?", a: "Absolutely not — it's against Yelp's Terms of Service and they actively investigate." },
      { q: "Do filtered reviews count toward my star rating?", a: "No. Only recommended reviews affect your visible average." },
      { q: "Should I focus on Yelp or Google?", a: "Google for most categories. Yelp matters in restaurants, services, and some metros (SF, NYC, Boston)." },
      { q: "How do I get a filtered review unfiltered?", a: "You can't directly. The reviewer needs to build profile trust by reviewing more places." },
    ],
  ),
  mk(
    "how-to-get-facebook-reviews",
    "Getting reviews",
    "How to get Facebook reviews (the modern Recommendations playbook)",
    "How to get Facebook reviews",
    "Facebook replaced star reviews with Recommendations. Here's how to collect them and turn them into social proof.",
    6,
    "Beginner",
    [
      "How Facebook Recommendations differ from stars",
      "How to enable reviews on your Page",
      "Where to embed Recommendations as social proof",
      "How to ask without sounding salesy",
    ],
    [
      "A Facebook Page (not a personal profile)",
      "Admin access to the Page",
    ],
    "Facebook quietly replaced star ratings with Recommendations — a yes/no thumbs-up system with a written component. The good news: Recommendations show up in Marketplace, Search, and friends' feeds, making them more social than Google reviews. Here's how to play the new system.",
    [
      {
        title: "Enable Reviews/Recommendations on your Page",
        body: "Go to Page Settings → Templates and Tabs → make sure 'Reviews' is enabled and visible. Without this step, customers literally cannot review you.",
        mistake: "Assuming the tab is on by default. New Pages often ship with it disabled.",
      },
      {
        title: "Write a compelling Page description with keywords",
        body: "Reviews surface in search. A Page with 'best wood-fired pizza in Austin' in the bio will pull better recommendations than a generic 'Italian restaurant'.",
      },
      {
        title: "Ask after a positive in-person moment",
        body: "When a customer compliments you in real life, say: 'You just made my day — would you mind sharing that on our Facebook page? Takes 30 seconds.' Most will.",
      },
      {
        title: "Send a single Messenger broadcast (if allowed)",
        body: "If customers messaged you in the last 24 hours, you can reply with a thank-you and a soft review ask. Outside that window, you can't broadcast.",
        mistake: "Mass-messaging unrelated followers. Facebook will rate-limit your Page.",
      },
      {
        title: "Embed top recommendations on your website",
        body: "Use Facebook's embed code to pull 3–5 best recommendations onto your homepage. Social proof from a recognizable platform converts.",
      },
      {
        title: "Cross-share to your personal network",
        body: "Ask your personal friends to recommend the business once. These show up to their friends' friends — huge organic reach.",
      },
    ],
    [
      { q: "Why don't I see star ratings anymore?", a: "Facebook deprecated stars in 2018 in favor of Recommendations. Old star ratings still count toward your historical score." },
      { q: "Can I delete a bad recommendation?", a: "Only if it violates Facebook's Community Standards. Otherwise, respond publicly and move on." },
      { q: "Do Facebook reviews help Google SEO?", a: "Indirectly — they create backlinks and social signals, but they don't show up in Google reviews." },
      { q: "How many recommendations do I need?", a: "20+ is the threshold where social proof kicks in for most browsers." },
      { q: "Can I incentivize recommendations?", a: "Facebook is less strict than Google but still prohibits incentivized reviews. Reward the action of reviewing, not the rating." },
    ],
  ),
  mk(
    "how-to-handle-fake-reviews",
    "Getting reviews",
    "How to handle fake reviews (Google, Yelp, and Facebook)",
    "How to handle fake reviews",
    "A step-by-step process for identifying, flagging, and getting fake reviews removed — without losing your mind.",
    8,
    "Intermediate",
    [
      "The five tell-tale signs of a fake review",
      "Exact wording for flag reports that get reviews removed",
      "How to use Yelp's and Google's escalation paths",
      "When to involve a lawyer (rarely)",
    ],
    [
      "Owner access to the review platform",
      "Order history or appointment records to prove non-customer status",
    ],
    "Fake reviews — from competitors, ex-employees, or extortion attempts — are infuriating and bad for business. Most can be removed if you know the process. Here's the practical, no-drama guide.",
    [
      {
        title: "Identify whether it's actually fake",
        body: "Real signs of fake: no order history, generic complaints, reviewer's history attacks similar businesses, posted in clusters, names competitors. Real customer with a bad day ≠ fake review.",
      },
      {
        title: "Screenshot everything immediately",
        body: "Capture the review, reviewer profile, posting date, and any other reviews they've left. Platforms sometimes remove reviews before you can document them.",
      },
      {
        title: "Flag the review with specifics",
        body: "Google: three dots → Report review → pick 'Conflict of interest' or 'Spam'. Yelp: 'Report Review' → cite ToS section. Be factual, not emotional.",
        tip: "Include order/appointment system dates in the flag explanation. Concrete proof gets removals.",
      },
      {
        title: "Respond publicly while waiting",
        body: "Until it's removed, respond calmly: 'We have no record of this customer in our system. We'd love to investigate — please reach out to owner@shop.com.' Future customers will read this.",
        mistake: "Calling the review fake aggressively in your response. Even if true, it reads badly.",
      },
      {
        title: "Use Google's escalation path",
        body: "If the flag is denied, go to Google Business Profile help, request a callback, and submit a 'Review removal request' with documentation. Persistence wins.",
      },
      {
        title: "For extortion attempts, contact platform Trust & Safety",
        body: "If someone threatens a bad review unless you pay, that's blackmail. Document everything and report to the platform's T&S team — and consider local police if explicit.",
      },
      {
        title: "Bury bad reviews with good ones",
        body: "While fighting removal, double down on collecting authentic reviews. One bad review among 5 is loud; among 50, it's noise.",
      },
    ],
    [
      { q: "How long does Google take to remove a flagged review?", a: "Typically 3–7 days for clear policy violations, longer for borderline cases." },
      { q: "Can I sue a fake reviewer?", a: "Possible but rarely worthwhile. Most platforms protect anonymity, and discovery is expensive." },
      { q: "What if a competitor is leaving fake reviews?", a: "Flag with 'Conflict of interest', include any evidence (matching IP, similar phrasing across competitors' pages), and escalate." },
      { q: "Can I leave fake positive reviews to balance it out?", a: "Never. Platforms detect this and you'll lose your page." },
      { q: "Does responding hurt my chances of removal?", a: "No — Google and Yelp's removal teams ignore owner responses when evaluating." },
    ],
  ),
  mk(
    "how-to-display-reviews-on-your-website",
    "Getting reviews",
    "How to display reviews on your website (and convert 2x more browsers)",
    "How to display reviews on your website",
    "Social proof on your homepage can lift conversion 20–40%. Here's the technical and design playbook.",
    9,
    "Intermediate",
    [
      "Three ways to display reviews (widget, embed, manual)",
      "How to add Review schema for rich snippets",
      "Which reviews to feature where",
      "Legal: what you can and can't quote",
    ],
    [
      "A website you can edit",
      "An existing pool of 5+ reviews on any platform",
    ],
    "A grid of real customer reviews on your homepage and product pages is one of the highest-ROI design changes you can make. Done right, it lifts conversion 20–40% and earns you star ratings in Google search results. Here's the full playbook.",
    [
      {
        title: "Pick your display method",
        body: "Option A: Embeddable widget (Trustpilot, Yotpo, Google Reviews widget) — easiest, pulls live data. Option B: Manual quotes with permission — most control. Option C: Custom build with the platform API — most flexible.",
      },
      {
        title: "Feature 3–5 reviews above the fold",
        body: "Don't bury reviews on a /testimonials page. Put them on the homepage near your CTA. Browsers scan for proof before clicking buy.",
        tip: "Use customer photos when you can — face-attached reviews convert 3x better.",
      },
      {
        title: "Add Review schema (JSON-LD)",
        body: "Mark up reviews with schema.org Review or AggregateRating. Google may show stars in search results, lifting CTR 30%+.",
        mistake: "Marking up reviews you don't actually display on the page. Google penalizes this.",
      },
      {
        title: "Quote specific outcomes, not adjectives",
        body: "'Got 47 new customers in 30 days' beats 'Amazing service'. Specific, quantified reviews convert better.",
      },
      {
        title: "Show the source",
        body: "'Verified Google review' or a small platform logo doubles believability. Anonymous quotes look fake.",
      },
      {
        title: "Rotate or paginate to feel fresh",
        body: "A static testimonial from 2019 hurts trust. Show recent reviews with dates or a 'last 30 days' filter.",
      },
      {
        title: "Get permission for direct quotes with names",
        body: "Reviews on public platforms can be displayed, but using a customer's full name and photo without permission can violate publicity rights in some states.",
      },
    ],
    [
      { q: "Will displaying reviews really lift conversion?", a: "Yes — most A/B tests show 10–40% conversion lift on pages with prominent social proof." },
      { q: "Do I have to display bad reviews too?", a: "If you're using a live widget, yes — but a 4.7 average looks more credible than a perfect 5.0." },
      { q: "What's the best plugin for WordPress?", a: "Trustindex and WP Review Slider both work well; for Shopify, look at Loox or Judge.me." },
      { q: "How many reviews before I should display?", a: "At least 5. Below that, it can hurt more than help." },
      { q: "Can I use AI-generated review snippets?", a: "Never. Misrepresentation is illegal under FTC endorsement guides." },
    ],
  ),
];

// ---------- SOCIAL MEDIA SETUP ----------
const SOCIAL_SETUP: Guide[] = [
  mk(
    "how-to-set-up-instagram-business-account",
    "Social media setup",
    "How to set up an Instagram Business account (step-by-step)",
    "How to set up an Instagram Business account",
    "Convert a personal profile to a Business account, unlock insights and ads, and configure it for discovery in under 10 minutes.",
    8,
    "Beginner",
    [
      "How Business vs. Creator vs. Personal differ",
      "How to unlock Instagram Insights",
      "How to add contact buttons and category",
      "How to link to a Facebook Page (still required for ads)",
    ],
    [
      "An existing Instagram account (personal is fine)",
      "A Facebook Page if you want to run ads later",
    ],
    "An Instagram Business account is free and unlocks insights, contact buttons, ads, and shopping. Switching takes five minutes. Here's the full setup with the configuration most owners miss.",
    [
      { title: "Open Settings and switch account type", body: "Profile → menu → Settings and privacy → Account type and tools → Switch to professional account. Pick 'Business' (not Creator) for most small businesses.", tip: "Creator is for personal-brand influencers. Business is for shops, services, restaurants." },
      { title: "Choose a category that customers search", body: "Pick the closest match — 'Coffee shop', 'Hair salon', 'Fitness trainer'. This affects discovery.", mistake: "Picking 'Public figure' or 'Brand' generically. Specific categories rank better." },
      { title: "Add contact methods", body: "Tap Edit profile → Contact options. Add phone, email, and address. These become tappable buttons on your profile." },
      { title: "Link to a Facebook Page", body: "Required if you want to run Meta ads. Settings → Linked accounts → Facebook. Create a Page if you don't have one." },
      { title: "Optimize your bio for search", body: "Bios are now keyword-searchable. Lead with what you do and where: 'Wood-fired pizza · East Austin · Open 5–10pm'." },
      { title: "Add a link-in-bio tool", body: "Use Linktree, Beacons, or build your own to send people to menu, booking, reviews. One link = many destinations." },
      { title: "Verify your insights are working", body: "Tap Insights at the top of your profile. You should see reach, impressions, and audience demographics within 24 hours." },
    ],
    [
      { q: "Will my followers see I switched?", a: "No — the switch is invisible to followers." },
      { q: "Can I switch back to personal?", a: "Yes, anytime. You'll lose access to insights." },
      { q: "Do I need a Facebook Page?", a: "Only for ads and Shopping. Otherwise no." },
      { q: "Why is my insights tab empty?", a: "It populates after 100 followers and a few posts." },
      { q: "Business or Creator for a solopreneur?", a: "Business if you sell products or services; Creator if you're building a personal media brand." },
    ],
  ),
  mk(
    "how-to-create-tiktok-business-account",
    "Social media setup",
    "How to create a TikTok Business account (and why it matters)",
    "How to create a TikTok Business account",
    "Switch to a Business account to unlock analytics, commercial music, and the ads platform.",
    7,
    "Beginner",
    [
      "What Business accounts unlock",
      "Why commercial music matters legally",
      "How to set up TikTok Shop (if eligible)",
      "Bio and link best practices",
    ],
    ["A TikTok account", "Phone access (verification required)"],
    "TikTok's Business account is free and removes legal risk around music while unlocking analytics. Setup is two minutes — but configuration matters.",
    [
      { title: "Switch to Business", body: "Profile → menu → Settings and privacy → Account → Switch to Business Account. Pick your industry." },
      { title: "Use Commercial Music Library", body: "Personal accounts can use trending songs; Business accounts cannot use copyrighted music. The Commercial Library has 500K+ cleared tracks.", mistake: "Posting a viral business video with copyrighted audio — TikTok will mute it." },
      { title: "Add a website link", body: "Available immediately for Business accounts. Send traffic to your homepage, booking page, or menu." },
      { title: "Apply for TikTok Shop if eligible", body: "US-based businesses with a tax ID can apply. In-feed shopping has driven huge GMV for small brands." },
      { title: "Optimize bio for search and intent", body: "TikTok search is now a major discovery engine. Use keywords: 'Brooklyn bakery 🥐 walk-ins welcome'." },
      { title: "Enable analytics tracking", body: "Profile → menu → Business Suite → Analytics. Review weekly for top-performing content." },
    ],
    [
      { q: "Do Business accounts get less reach?", a: "Slightly — many creators report a small reach dip, but analytics and legal music access usually outweigh it." },
      { q: "Can I use trending sounds at all?", a: "Only sounds in the Commercial Library are safe; others can be muted." },
      { q: "Do I need a website?", a: "Not required, but Business accounts get a link slot in bio." },
      { q: "How do I get verified?", a: "Verification is invite-only based on growth and authenticity — not paid." },
      { q: "Should small businesses post daily?", a: "Aim for 3–5x per week, prioritizing quality and watch time." },
    ],
  ),
  mk(
    "how-to-optimize-google-business-profile",
    "Social media setup",
    "How to optimize your Google Business Profile (full 2026 checklist)",
    "How to optimize your Google Business Profile",
    "The 14-point checklist that boosts local pack rankings and click-through from search.",
    10,
    "Intermediate",
    [
      "Why GBP is the highest-ROI local SEO asset",
      "Every field that affects ranking",
      "How to use Posts, Q&A, and Products",
      "How to monitor and react to changes",
    ],
    ["A claimed Google Business Profile", "A phone for verification"],
    "Google Business Profile (formerly Google My Business) is the single most important local marketing asset. A fully optimized profile can double your call volume. Here's the complete checklist.",
    [
      { title: "Verify ownership", body: "Postcard, phone, email, or video verification. Without verification, you cannot edit anything that matters." },
      { title: "Pick the most specific primary category", body: "'Italian restaurant' beats 'Restaurant'. Add 2–4 secondary categories for related searches." },
      { title: "Write a keyword-rich business description", body: "750 characters. Lead with what you do and where. Mention top services naturally." },
      { title: "Upload 10+ high-quality photos", body: "Cover, logo, interior, exterior, team, products. Photos drive 35% more clicks." },
      { title: "Add hours, including special hours", body: "Holiday hours, seasonal closures. Wrong hours = trust killer." },
      { title: "Enable messaging", body: "Customers can text you from your listing. Respond within an hour or disable it." },
      { title: "Use Posts weekly", body: "Treat Posts like a free ad — what's new, what's on sale, an event. Recent activity signals to Google your business is alive." },
      { title: "Seed Q&A with common questions", body: "You can post your own Q&A. Add 5–10 FAQs with answers. Customers can also ask — monitor weekly." },
      { title: "Add Services and Products", body: "Each service is its own discoverable page. Add price, description, and a photo." },
      { title: "Build a steady stream of reviews", body: "Aim for 1–3 new reviews per week. Frequency matters more than total." },
      { title: "Respond to every review", body: "Thank positives, calmly address negatives. Response rate is a ranking signal." },
      { title: "Add booking and ordering links", body: "Reservation, appointment, or order-ahead integrations turn the listing into a conversion page." },
      { title: "Add attributes", body: "Women-owned, wheelchair accessible, free Wi-Fi, etc. These power filtered searches." },
      { title: "Monitor Insights monthly", body: "Track searches, calls, direction requests. Adjust based on what's working." },
    ],
    [
      { q: "How long does it take to rank?", a: "Optimization shows results in 30–90 days. Reviews are the slowest but highest-impact lever." },
      { q: "Can I change my business name to add keywords?", a: "No — that's a Google policy violation and often gets the listing suspended." },
      { q: "What if my listing gets suspended?", a: "File a reinstatement request through Business Profile Help. Be patient — can take weeks." },
      { q: "Does posting daily help?", a: "Diminishing returns after 2–3x per week." },
      { q: "Do photos really matter?", a: "Massively — listings with 100+ photos get 520% more calls than those with few." },
    ],
  ),
  mk(
    "how-to-create-a-facebook-business-page",
    "Social media setup",
    "How to create a Facebook Business Page (and configure it right)",
    "How to create a Facebook Business Page",
    "Create your Page, claim your vanity URL, and set up the essentials in 15 minutes.",
    8,
    "Beginner",
    [
      "Page vs. profile vs. group",
      "Required setup for ads eligibility",
      "Templates and CTAs",
      "Inviting your network",
    ],
    ["A personal Facebook account", "Business logo and cover image"],
    "A Facebook Business Page is still required for Meta ads, Instagram shopping, and many integrations. Here's a no-frills setup.",
    [
      { title: "Create the Page", body: "facebook.com/pages/create → fill in name, category, description. Use your real legal or DBA name." },
      { title: "Add profile and cover photos", body: "Profile: 170×170, ideally your logo. Cover: 820×312, a real photo of your space or product." },
      { title: "Pick a Page template", body: "Templates control which tabs and buttons appear. Pick 'Business', 'Restaurants & Cafés', or 'Services' based on your model." },
      { title: "Set your call-to-action button", body: "Book Now, Call, Shop Now, Sign Up. Pick the one action you most want." },
      { title: "Claim a vanity URL", body: "Settings → Username. facebook.com/yourbusinessname is more shareable." },
      { title: "Add your full business info", body: "Hours, phone, email, address, website. Fill every field." },
      { title: "Invite friends and existing customers", body: "Page → three dots → Invite friends. One-time push to get your first 50 likes." },
      { title: "Publish 3–5 posts before you promote", body: "An empty Page hurts conversion. Post photos, an intro, and a few customer highlights first." },
    ],
    [
      { q: "Do Pages get organic reach anymore?", a: "Very little — usually 2–6%. Treat the Page as a credibility asset and ad landing zone." },
      { q: "Can I run ads without a Page?", a: "No — every Meta ad must run from a Page." },
      { q: "What about Facebook Groups?", a: "Groups are great for community but separate from Pages." },
      { q: "How do I link Instagram?", a: "Meta Business Suite → Settings → Linked accounts." },
      { q: "Should I cross-post the same content?", a: "Often yes — most followers only see one platform." },
    ],
  ),
  mk(
    "how-to-link-instagram-and-facebook",
    "Social media setup",
    "How to link Instagram and Facebook (the correct 2026 way)",
    "How to link Instagram and Facebook",
    "Connect both accounts through Meta Business Suite so you can cross-post, run ads, and use Shopping.",
    6,
    "Beginner",
    [
      "Why linking is required for ads",
      "Meta Accounts Center vs. legacy linking",
      "How to verify the link",
      "Common 'account already linked' errors",
    ],
    ["A Facebook Page", "An Instagram account", "Admin access to both"],
    "Meta unified its linking flow through Accounts Center. Here's the modern, no-broken-links process.",
    [
      { title: "Open Meta Accounts Center", body: "From Facebook or Instagram → Settings → Accounts Center. This is the modern hub." },
      { title: "Add accounts", body: "Click 'Add accounts' → pick Instagram and Facebook. Sign in to both." },
      { title: "Choose what to sync", body: "Profile photo, stories, posts, ads. Pick selectively to keep brands distinct if needed." },
      { title: "Connect Page to Instagram explicitly", body: "Page → Settings → Linked accounts → Instagram. This second link enables ads and shopping." },
      { title: "Verify in Meta Business Suite", body: "business.facebook.com → Settings. You should see both accounts under your business." },
      { title: "Fix 'already linked' errors", body: "If Instagram says it's linked to another Page, log into the old Page and unlink first." },
    ],
    [
      { q: "Why do I need both links?", a: "Accounts Center links your identities; Page → Instagram link enables ad and commerce features." },
      { q: "Can I cross-post automatically?", a: "Yes — in publishing tools, toggle 'Share to Facebook'." },
      { q: "Will linking expose my personal account?", a: "No — only your business identities are linked." },
      { q: "Can I unlink later?", a: "Yes, anytime." },
      { q: "What if I don't have a Facebook Page?", a: "Create one — it's required for Meta ads even if you barely use Facebook." },
    ],
  ),
  mk(
    "how-to-set-up-pinterest-business-account",
    "Social media setup",
    "How to set up a Pinterest Business account",
    "How to set up a Pinterest Business account",
    "Pinterest drives high-intent traffic for visual products. Here's the full setup and first 5 boards.",
    7,
    "Beginner",
    [
      "Why Pinterest is a search engine, not social media",
      "Claiming your website",
      "Rich Pins setup",
      "First-30-days board strategy",
    ],
    ["A Pinterest account", "Access to your website's <head>"],
    "Pinterest is functionally a visual search engine with massive intent — people plan purchases there. For visual businesses (home, fashion, food, weddings, DIY) it's underpriced traffic.",
    [
      { title: "Convert to a Business account", body: "Settings → Account management → Convert to business." },
      { title: "Claim your website", body: "Settings → Claimed accounts → Claim. Add a meta tag or HTML file. This unlocks analytics from your domain." },
      { title: "Enable Rich Pins", body: "Rich Pins pull metadata (price, availability, description) from your site automatically. Apply via Pinterest's validator." },
      { title: "Create 5 starter boards", body: "Each board = a topic, not your brand. 'Small kitchen ideas' beats 'Our products'." },
      { title: "Pin 5–10 per board to start", body: "Mix your own content and reputable third-party content. Empty boards rank poorly." },
      { title: "Write keyword-rich pin descriptions", body: "Pinterest is search — describe what's in the image and who it's for." },
      { title: "Schedule with native tools", body: "Use Pinterest's scheduler (free) or Tailwind for consistency." },
    ],
    [
      { q: "How long until Pinterest sends traffic?", a: "60–120 days. Pinterest pins have long shelf lives — a viral pin can drive traffic for years." },
      { q: "Should I use video pins?", a: "Yes — Idea Pins (now Pinterest's video format) get prioritized in the feed." },
      { q: "What sizes work best?", a: "2:3 vertical (1000×1500) for standard pins." },
      { q: "Can I link directly to products?", a: "Yes — that's the whole point. Every pin should link to a destination." },
      { q: "Is Pinterest worth it for B2B?", a: "Rarely — Pinterest is consumer-heavy." },
    ],
  ),
];

// ---------- CONTENT CREATION ----------
const CONTENT: Guide[] = [
  mk(
    "how-to-write-better-instagram-captions",
    "Content creation",
    "How to write better Instagram captions (with 10 templates)",
    "How to write better Instagram captions",
    "The hook, story, CTA framework that takes captions from skipped to saved — plus 10 plug-and-play templates.",
    7,
    "Beginner",
    [
      "The 3-line hook rule",
      "Saves vs. likes — which matters more in 2026",
      "When to use emojis (and when not to)",
      "How to write CTAs that don't sound desperate",
    ],
    ["An Instagram account", "Recent posts to rewrite for practice"],
    "Instagram's algorithm rewards saves and sends — both come from captions, not images. A great caption can 5x reach on the same photo.",
    [
      { title: "Lead with a hook in line 1", body: "Instagram truncates after ~125 characters. Your first line must earn the 'more' tap.", tip: "Hooks that work: contrarian statements, specific numbers, questions readers can't ignore." },
      { title: "Use white space", body: "A wall of text gets skipped. Break every 1–2 sentences. Use line breaks generously." },
      { title: "Tell one micro-story", body: "Captions that tell a single, specific story (one customer, one moment, one lesson) outperform broad lists." },
      { title: "Add a clear CTA", body: "'Save this for later' or 'Tag a friend who needs this' beats 'Link in bio'." },
      { title: "Use 3–8 hyper-relevant hashtags", body: "Niche hashtags (10K–500K posts) outperform broad ones. Avoid the 30-tag spam." },
      { title: "Edit ruthlessly", body: "Read aloud. Cut anything that doesn't earn its space." },
      { title: "Test caption length", body: "Long-form (1500+ chars) wins for educational content; short for product/aesthetic." },
    ],
    [
      { q: "Does the algorithm read captions?", a: "Yes — Instagram surfaces posts based on caption keywords now." },
      { q: "Should I use emojis?", a: "1–3 max, ideally as visual breaks. Avoid emoji vomit." },
      { q: "How important are hashtags?", a: "Less than 2 years ago, but still useful for niche discovery." },
      { q: "Can I edit captions later?", a: "Yes, but heavy edits within minutes of posting can hurt reach." },
      { q: "What about call-to-comment posts?", a: "Comments are a strong ranking signal — questions in captions often work." },
    ],
  ),
  mk(
    "how-to-make-tiktok-videos-for-small-business",
    "Content creation",
    "How to make TikTok videos for a small business (no fancy gear)",
    "How to make TikTok videos for a small business",
    "A repeatable 5-shot framework you can film in 10 minutes on your phone.",
    8,
    "Beginner",
    [
      "Why watch time matters more than views",
      "The 5-shot framework",
      "Best-performing hook formulas",
      "How to repurpose to Reels and Shorts",
    ],
    ["A smartphone", "TikTok Business account", "10 minutes per video"],
    "TikTok rewards storytelling, not production value. The best-performing small business videos are filmed in minutes on a phone. Here's the system.",
    [
      { title: "Pick one specific topic per video", body: "'How we prep dough at 4am' beats 'Welcome to our bakery'. Specificity drives watch time." },
      { title: "Open with a strong hook in 1 second", body: "'This is what $5 of ingredients turns into.' Hooks decide everything." },
      { title: "Film 5 short shots", body: "Wide, medium, close-up, action, payoff. Variety = retention." },
      { title: "Add on-screen text for the hook", body: "60%+ watch with sound off. Captions on-screen are non-negotiable." },
      { title: "Edit tight — under 30 seconds when possible", body: "Cut every dead moment. Pace = watch time." },
      { title: "Use the commercial music library", body: "Personal sounds risk muting. Trending commercial-cleared sounds work fine." },
      { title: "Post consistently and study analytics", body: "3–5x per week. Double down on what gets 4-second+ average watch time." },
    ],
    [
      { q: "Does length matter?", a: "30–60s sweet spot for most small business content. Longer works only if pacing is tight." },
      { q: "Do I need a tripod?", a: "Helpful, not required. A propped phone works." },
      { q: "What about lighting?", a: "Natural light is free and best." },
      { q: "How long until I see results?", a: "Most accounts get a hit in 10–30 posts." },
      { q: "Can I cross-post to Reels?", a: "Yes — remove the TikTok watermark first (free apps do this)." },
    ],
  ),
  mk(
    "how-to-take-better-product-photos-with-phone",
    "Content creation",
    "How to take better product photos with your phone",
    "How to take better product photos with your phone",
    "Light, angle, and edit — three settings and three rules for studio-quality product shots without a camera.",
    6,
    "Beginner",
    [
      "Why window light beats any ring light",
      "The diffuser trick (under $5)",
      "Phone camera settings to change",
      "Free editing apps that finish the job",
    ],
    ["A smartphone from the last 3 years", "Natural light access"],
    "You don't need a DSLR. Modern phone cameras + window light + a free editor will produce shots good enough for Instagram, Amazon, and your website.",
    [
      { title: "Shoot near a window during 'golden hour'", body: "An hour after sunrise or before sunset. Soft, directional, free." },
      { title: "Diffuse harsh light with a white sheet", body: "A bedsheet over a sunny window = $500 softbox. Photographers' biggest secret." },
      { title: "Turn off your phone's auto-HDR for products", body: "HDR can flatten color. For product, manual exposure or pro mode wins." },
      { title: "Shoot at 1x or 2x — never digital zoom", body: "Digital zoom destroys quality. Move closer instead." },
      { title: "Use the rule of thirds", body: "Turn on grid. Place subject on an intersection, not dead center." },
      { title: "Edit in Lightroom Mobile (free)", body: "Adjust exposure, contrast, white balance. Don't over-edit. Save a preset for consistency." },
      { title: "Shoot in batches", body: "Set up once, photograph 10 products. Consistent lighting across your feed." },
    ],
    [
      { q: "iPhone or Android?", a: "Both are excellent now. Don't upgrade for photos." },
      { q: "Do I need a ring light?", a: "Rarely — natural light is better." },
      { q: "Should I shoot in RAW?", a: "Only if you'll edit in Lightroom. Otherwise HEIC/JPEG is fine." },
      { q: "What about background?", a: "White foam board from any craft store works for 99% of products." },
      { q: "How do I get a pure white background?", a: "Adjust exposure to +0.7 and use the levels tool in editing." },
    ],
  ),
  mk(
    "how-to-create-a-content-calendar",
    "Content creation",
    "How to create a content calendar (template included)",
    "How to create a content calendar",
    "A 30-minute setup that prevents 'what do I post today?' forever.",
    8,
    "Beginner",
    [
      "Why batching saves 5+ hours a week",
      "The 4-bucket content framework",
      "Tools (Notion, Sheets, Trello)",
      "How to plan a quarter in one sitting",
    ],
    ["A spreadsheet or Notion", "1 hour for the initial build"],
    "The reason most small businesses post inconsistently is decision fatigue. A simple content calendar fixes it permanently.",
    [
      { title: "Pick a tool", body: "Notion, Google Sheets, or Trello. Don't overthink it — the system matters more than the tool." },
      { title: "Define your 4 buckets", body: "Most brands: Educate, Inspire, Promote, Behind-the-scenes. Rotate evenly." },
      { title: "Build your weekly rhythm", body: "Mon: behind-the-scenes. Tue: educate. Wed: promote. Etc. Predictability builds audience habit." },
      { title: "Brainstorm 30 ideas in one sitting", body: "30 minutes, no filter. You're filling 30 days." },
      { title: "Slot ideas into the calendar", body: "Assign each idea to a bucket and date." },
      { title: "Batch-create on Sundays", body: "Film 5 videos and write 10 captions in one 2-hour block. Saves hours daily." },
      { title: "Review monthly", body: "What performed? What didn't? Adjust the next month's mix." },
    ],
    [
      { q: "How far ahead should I plan?", a: "30 days is the sweet spot — long enough for batching, short enough to stay flexible." },
      { q: "What if a trend pops up?", a: "Have one 'wildcard' slot per week for reactive content." },
      { q: "Do I need separate calendars per platform?", a: "One calendar with platform tags is easier." },
      { q: "Best tools for teams?", a: "Notion, Asana, or Airtable scale better than spreadsheets." },
      { q: "How do I avoid burnout?", a: "Batch creation + take a planned week off every quarter." },
    ],
  ),
  mk(
    "how-to-batch-create-social-media-content",
    "Content creation",
    "How to batch-create a month of social content in one day",
    "How to batch-create social media content",
    "The studio-day workflow that turns 8 hours into 30 posts.",
    9,
    "Intermediate",
    [
      "Why context-switching kills creative speed",
      "Pre-batch prep (the night before)",
      "The film-first, edit-later sequence",
      "Tools to schedule the output",
    ],
    ["A content calendar with 30 ideas", "Phone, props, outfits if applicable"],
    "Batching is the difference between 'I posted 4 times this month' and 'I have 30 posts queued'. Here's the studio-day playbook used by top SMB creators.",
    [
      { title: "Prep the night before", body: "Print the 30 ideas. Assemble props, outfits, products. Charge devices." },
      { title: "Film all video first", body: "Block 3 hours. Run through your shot list without editing. Context-switching between film and edit kills speed." },
      { title: "Photograph all stills next", body: "Same lighting setup, knock out 30 product shots in 90 minutes." },
      { title: "Write all captions in one block", body: "Write 30 captions in 60 minutes. Don't edit yet — just draft." },
      { title: "Edit videos in a 90-minute block", body: "CapCut, InShot, or native editor. One template = fast." },
      { title: "Edit photos in a 30-minute block", body: "Lightroom preset applied to all. Consistency = brand." },
      { title: "Schedule all 30 posts", body: "Meta Business Suite (free), Buffer, or Later. Set and forget for a month." },
    ],
    [
      { q: "How long does a full studio day take?", a: "Most owners do 30 posts in 6–8 hours, once the system is dialed." },
      { q: "Can I batch on a phone alone?", a: "Yes — CapCut + a tripod is all you need." },
      { q: "What if I run out of ideas mid-day?", a: "Stop and brainstorm again. Don't post weak content to fill slots." },
      { q: "How do I keep content from feeling stale?", a: "Mix in 1–2 reactive posts per week alongside batched content." },
      { q: "Best music to batch to?", a: "Whatever keeps you in flow. Many creators swear by film scores." },
    ],
  ),
  mk(
    "how-to-find-trending-hashtags",
    "Content creation",
    "How to find trending hashtags (without falling for fake ones)",
    "How to find trending hashtags",
    "Three free methods to identify high-intent hashtags that actually drive reach.",
    6,
    "Beginner",
    [
      "Why broad hashtags hurt reach",
      "The 3-tier hashtag stack (broad/niche/branded)",
      "Native discovery tools per platform",
      "How to track which hashtags work",
    ],
    ["Active accounts on the platforms you target"],
    "Most hashtag advice is outdated. Here's how to find tags that actually move the needle in 2026.",
    [
      { title: "Build a 3-tier stack", body: "1 broad (#smallbusiness, 50M+ posts), 4 niche (#brooklynbakery, 50K–500K), 3 branded (#yourshopname). Mix wins." },
      { title: "Use Instagram's native search", body: "Type a niche tag in search → Tags tab → see related tags and post volumes." },
      { title: "Use TikTok's Creative Center", body: "ads.tiktok.com/business/creativecenter — shows trending hashtags by region with growth %." },
      { title: "Check Pinterest Trends", body: "trends.pinterest.com — shows seasonal trends 6 months out." },
      { title: "Audit competitor posts", body: "What hashtags do similar-sized accounts use on their best posts? Steal selectively." },
      { title: "Track which tags drive saves and reach", body: "Use Instagram Insights → see which hashtags brought non-followers." },
      { title: "Rotate every 30 days", body: "Same hashtag set forever signals spam. Refresh quarterly." },
    ],
    [
      { q: "How many hashtags should I use?", a: "Instagram: 3–8. TikTok: 3–5. Pinterest: 4–8. More isn't better." },
      { q: "Are hashtags dead?", a: "No, but they're less powerful than 2020. They're a multiplier, not a strategy." },
      { q: "Should I put hashtags in caption or first comment?", a: "Caption — Instagram has confirmed both work equally." },
      { q: "Banned hashtags?", a: "Yes — they exist and tank reach. Check tools like Display Purposes." },
      { q: "What's a good hashtag size to target?", a: "10K–500K posts is the sweet spot for visibility without drowning." },
    ],
  ),
];

// ---------- CUSTOMER ACQUISITION ----------
const ACQUISITION: Guide[] = [
  mk(
    "how-to-get-your-first-100-customers",
    "Customer acquisition",
    "How to get your first 100 customers (without ads)",
    "How to get your first 100 customers",
    "A scrappy, repeatable playbook for hitting the magic 100-customer milestone organically.",
    10,
    "Beginner",
    [
      "Why the first 100 are different",
      "5 zero-budget acquisition channels",
      "How to ask for referrals at customer 1",
      "When to stop scrappy and start systematic",
    ],
    ["A product or service that's launchable", "Time and hustle"],
    "The first 100 customers cannot be bought efficiently with ads — your funnel isn't tuned yet. They must be earned, one at a time, in ways that don't scale. That's a feature, not a bug.",
    [
      { title: "Sell to 10 people you know personally", body: "Friends, family, ex-coworkers. The first 10 should be a phone call, not a marketing campaign." },
      { title: "Show up where your customers already are", body: "Local meetup, Facebook group, subreddit, Discord. Be helpful first, sell second." },
      { title: "DM 50 ideal customers individually", body: "Personalized DMs convert 5–20x ad clicks. Slow but effective at small scale." },
      { title: "Offer a 'founding customer' deal", body: "Time-limited, lifetime price lock, named on a wall. Scarcity + status." },
      { title: "Ask every customer for one referral", body: "After delivering value, ask: 'Do you know one other person who'd benefit?' Most will say yes." },
      { title: "Partner with one complementary business", body: "Find a non-competing business with your customer. Cross-promote." },
      { title: "Document everything for case studies", body: "Customer 1 → 100 are your future testimonials. Capture stories early." },
      { title: "Track every channel", body: "Note where each customer came from. Past 50, double down on the winning channel." },
    ],
    [
      { q: "How long should it take?", a: "Most lean startups take 60–180 days from launch." },
      { q: "Should I run ads to get to 100?", a: "Usually no — ads need a tuned funnel and tracking. Earn the first 100 manually." },
      { q: "What if I run out of network?", a: "Cold outreach. 50 personalized DMs per day for two weeks fills the gap." },
      { q: "When is it time to scale?", a: "When you have a repeatable acquisition channel and 70%+ retention." },
      { q: "Should I give a discount?", a: "Yes — founding-member pricing is worth the trade for momentum." },
    ],
  ),
  mk(
    "how-to-run-a-successful-giveaway",
    "Customer acquisition",
    "How to run a successful giveaway (without attracting freebie-hunters)",
    "How to run a successful giveaway",
    "The framework that grows real customers — not contest-hopping accounts who unfollow the next day.",
    9,
    "Intermediate",
    [
      "Why most giveaways fail to grow real customers",
      "Prize selection that filters for ideal customers",
      "Legal compliance (it's required)",
      "How to convert entrants into customers",
    ],
    [
      "A prize worth $50+ that your target customer wants",
      "A platform to host the giveaway",
      "An email or SMS capture mechanism",
    ],
    "Most giveaways grow vanity metrics. A well-designed one grows real customers. The difference is the prize.",
    [
      { title: "Pick a prize only your ideal customer wants", body: "An iPad attracts everyone. A $200 store credit attracts your future customer. Niche prize = niche audience." },
      { title: "Set entry friction (not too low)", body: "Low friction = freebie hunters. Email + one social action is the sweet spot." },
      { title: "Write clear, legal rules", body: "No purchase necessary, age requirement, region, end date, winner selection. Required by law in most regions." },
      { title: "Promote across owned channels", body: "Email list, social, in-store signage. Don't rely on virality." },
      { title: "Use a giveaway tool", body: "Gleam, KingSumo, or Vyper handle entry verification, drawing, and notification." },
      { title: "Pick the winner publicly", body: "Live video selection or screen-recorded random.org. Trust requires transparency." },
      { title: "Give all entrants a consolation offer", body: "Everyone who didn't win gets 15% off. This is where revenue lives." },
      { title: "Email the list for 30 days post-giveaway", body: "Most conversions happen in the 30 days after, not during. Sequence it." },
    ],
    [
      { q: "Are giveaways legal?", a: "Yes, with rules. Avoid 'consideration' (no purchase necessary) and follow state/country sweepstakes laws." },
      { q: "What's the best platform?", a: "Instagram for awareness, email for conversion. Run both." },
      { q: "How long should it run?", a: "1–2 weeks max. Longer = momentum dies." },
      { q: "Should I require a follow?", a: "Be careful — Instagram doesn't allow requiring a follow as an entry method (though many do)." },
      { q: "Will all my new followers unfollow?", a: "Some will. That's fine. The 20% who stay are real customers." },
    ],
  ),
  mk(
    "how-to-start-an-affiliate-program",
    "Customer acquisition",
    "How to start an affiliate program (zero to first sale)",
    "How to start an affiliate program",
    "Set up tracking, commission, and recruitment in a week. No agency required.",
    10,
    "Intermediate",
    [
      "Affiliate vs. influencer vs. referral",
      "Commission structures that don't kill margin",
      "Tracking tech that actually works",
      "How to recruit your first 10 affiliates",
    ],
    [
      "A product or service with a clear conversion event",
      "Margin that supports 10–30% commission",
    ],
    "An affiliate program is performance marketing on autopilot — you only pay when sales happen. Setup is straightforward once you make a few key decisions.",
    [
      { title: "Pick your commission structure", body: "Flat fee per sale, % of revenue, or recurring. Most SaaS does 20–30% recurring; e-commerce 10–15% flat." },
      { title: "Choose a tracking platform", body: "Rewardful, Tapfiliate, Refersion, PartnerStack. Pick based on your platform (Stripe, Shopify, WooCommerce)." },
      { title: "Set program rules clearly", body: "Cookie window, attribution model, prohibited promotion methods (coupon sites, brand bidding). Write a 1-page T&C." },
      { title: "Build a simple affiliate landing page", body: "What you sell, commission, how to apply, FAQs. Linked from your footer." },
      { title: "Create affiliate assets", body: "Logos, banner images, sample copy, swipe emails. Lower friction = more sales." },
      { title: "Recruit your first 10 affiliates personally", body: "Reach out to existing happy customers and bloggers in your niche. Personalized > public application." },
      { title: "Pay reliably and on time", body: "Monthly is standard. Late payments = dead program." },
      { title: "Run a quarterly affiliate sprint", body: "Bonus commission, new creative, limited-time. Spike performance every 90 days." },
    ],
    [
      { q: "Affiliate vs. influencer?", a: "Affiliates earn on actual sales tracked via links. Influencers usually paid for posts." },
      { q: "What's a good commission?", a: "10–30% depending on margin. Higher for digital, lower for physical." },
      { q: "Do I need a coupon code?", a: "Optional. Codes work great for offline conversions but cannibalize organic discounts." },
      { q: "Legal disclosures?", a: "Yes — FTC requires affiliates to disclose. Include it in your terms." },
      { q: "Best platform for Shopify?", a: "Refersion, Goaffpro, or UpPromote integrate well." },
    ],
  ),
  mk(
    "how-to-launch-a-referral-program",
    "Customer acquisition",
    "How to launch a referral program (that customers actually use)",
    "How to launch a referral program",
    "Give-X-get-X mechanics, friction tradeoffs, and the messaging that drives 30%+ acquisition from referrals.",
    9,
    "Intermediate",
    [
      "Referral vs. affiliate (when to pick which)",
      "Give-X-get-X math",
      "Where to ask (and where not to)",
      "Measuring true ROI",
    ],
    ["A repeat-purchase business model", "An existing happy customer base"],
    "Referrals are the highest-converting acquisition channel for almost every consumer business — and the most under-built. Here's a clean launch path.",
    [
      { title: "Pick a give-X-get-X structure", body: "$10 for referrer, $10 for new customer. Symmetric, easy to remember, easy to share." },
      { title: "Make the math work for your unit economics", body: "Total reward < 50% of CAC. If CAC is $40, $15+$15 works; $30+$30 doesn't." },
      { title: "Use a referral platform", body: "ReferralCandy, Friendbuy, Yotpo. Or build with Stripe + a tracking link." },
      { title: "Promote at the highest-affinity moments", body: "Order confirmation page, post-delivery email, after a positive support interaction." },
      { title: "Make sharing one tap", body: "Native share sheet, pre-written message, unique link. Friction kills shares." },
      { title: "A/B test the reward", body: "Run cash vs. credit vs. product. Store credit usually wins on retention." },
      { title: "Email referrers monthly with their earnings", body: "'You've earned $40 in credit — share again' = reactivation engine." },
    ],
    [
      { q: "Referral or affiliate program?", a: "Referral = customers refer friends. Affiliate = creators/partners refer audiences. Run both eventually." },
      { q: "What's a good referral conversion rate?", a: "10–30% of share clicks convert, much higher than organic." },
      { q: "Cash or credit?", a: "Credit. Cash payouts cost more and lower retention." },
      { q: "Should I require the friend to be new?", a: "Yes — to prevent abuse." },
      { q: "When should I launch?", a: "After you have 100+ happy customers who'd recommend you." },
    ],
  ),
  mk(
    "how-to-build-an-email-list-from-scratch",
    "Customer acquisition",
    "How to build an email list from scratch (0 to 1,000 subscribers)",
    "How to build an email list from scratch",
    "The lead magnet, opt-in, and welcome sequence that turn cold traffic into an owned audience.",
    10,
    "Beginner",
    [
      "Why email beats every social platform for ROI",
      "Lead magnets that actually convert",
      "How to design a 5-email welcome sequence",
      "Tools that work for under $20/mo",
    ],
    ["A website or landing page", "An email tool (Mailchimp, ConvertKit, Beehiiv)"],
    "Email is the only marketing channel you fully own. The platform you build there can't be deleted by an algorithm change. Start now.",
    [
      { title: "Pick an email tool", body: "Beehiiv, ConvertKit, Mailchimp, or Klaviyo (e-commerce). All have free tiers." },
      { title: "Create a high-value lead magnet", body: "Checklist, template, mini-course, discount. Solves one specific problem your customer has." },
      { title: "Build a single-purpose landing page", body: "Headline, value, form. No menu, no distractions. Conversion rates 20–40%." },
      { title: "Drive traffic from social, search, and partnerships", body: "Promote the lead magnet, not your homepage." },
      { title: "Set up a 5-email welcome sequence", body: "Welcome → story → social proof → product → ask. Sent over 7 days." },
      { title: "Send a weekly newsletter", body: "Pick a day, never miss it. Consistency builds trust." },
      { title: "Clean the list quarterly", body: "Remove unengaged subscribers. Better deliverability beats vanity numbers." },
    ],
    [
      { q: "How fast can I get to 1,000?", a: "60–180 days with daily promotion of a good lead magnet." },
      { q: "Should I buy a list?", a: "Never. Illegal in many regions and destroys deliverability." },
      { q: "What's a good open rate?", a: "30%+ in 2026. Below 20% = list or subject line problem." },
      { q: "How often should I email?", a: "Weekly minimum. Otherwise you become a stranger." },
      { q: "What about SMS?", a: "Add it as a second channel once email is dialed." },
    ],
  ),
  mk(
    "how-to-collect-customer-data-legally",
    "Customer acquisition",
    "How to collect customer data legally (GDPR, CCPA, CAN-SPAM)",
    "How to collect customer data legally",
    "A non-lawyer's guide to consent, storage, and disclosure that keeps your small business out of trouble.",
    10,
    "Intermediate",
    [
      "The three laws every US/EU business must follow",
      "Consent vs. legitimate interest",
      "What you must disclose in your privacy policy",
      "Data minimization (collect less, sleep better)",
    ],
    [
      "A website that collects any user data",
      "An attorney for the final review (this guide isn't legal advice)",
    ],
    "This is not legal advice — get a lawyer for your specific situation. But here are the foundational practices every small business should follow.",
    [
      { title: "Map every data point you collect", body: "Email, name, IP, payment, behavior. You can't protect what you haven't inventoried." },
      { title: "Collect only what you need", body: "Data minimization. Birthday isn't required for a newsletter. Less data = less liability." },
      { title: "Get explicit, granular consent", body: "Separate checkboxes for marketing, newsletter, analytics. Pre-checked boxes are illegal in EU." },
      { title: "Publish a clear privacy policy", body: "What you collect, why, with whom you share, how to delete. Plain English." },
      { title: "Add a cookie banner that respects choice", body: "EU/UK requires opt-in for non-essential cookies. CCPA: opt-out for sale." },
      { title: "Honor deletion and access requests", body: "Build a process to retrieve and delete a user's data within 30 days." },
      { title: "Secure data appropriately", body: "Encrypt at rest and in transit. Don't store passwords in plaintext. Don't email spreadsheets of customer data." },
      { title: "Include unsubscribe in every marketing email", body: "Required by CAN-SPAM, GDPR, and basic decency." },
    ],
    [
      { q: "Does GDPR apply to US businesses?", a: "Yes — if you have EU users. Geolocation doesn't help." },
      { q: "Do I need a cookie banner?", a: "If you have EU/UK users or use non-essential cookies, yes." },
      { q: "What's the fine for non-compliance?", a: "GDPR: up to 4% of global revenue. CCPA: per-violation fines." },
      { q: "Can I send a cold email?", a: "B2B is often allowed; B2C usually requires opt-in. Region-dependent." },
      { q: "Where do I host my privacy policy?", a: "Footer link, accessible from every page." },
    ],
  ),
];

// ---------- ANALYTICS & GROWTH ----------
const ANALYTICS: Guide[] = [
  mk(
    "how-to-measure-marketing-roi",
    "Analytics & growth",
    "How to measure marketing ROI (simple model that actually works)",
    "How to measure marketing ROI",
    "A spreadsheet model for tracking marketing dollars in and revenue out — without enterprise tooling.",
    9,
    "Intermediate",
    [
      "The simple ROI formula (and its limits)",
      "Attribution: first-touch, last-touch, multi-touch",
      "How to handle long sales cycles",
      "When ROI lies (and what to track instead)",
    ],
    ["Marketing spend records", "Revenue records", "A spreadsheet"],
    "ROI is the conversation every owner wants — and the one most agencies dodge. A simple, honest model beats a fancy dashboard.",
    [
      { title: "Sum total marketing spend per channel per month", body: "Ads, tools, content, agency. Hidden costs (your time) count too." },
      { title: "Attribute revenue per channel", body: "Use UTM links and ask customers 'how did you find us?' at checkout." },
      { title: "Calculate ROI: (Revenue − Cost) / Cost", body: "100% ROI = doubled money. Most healthy channels are 200%+ over time." },
      { title: "Pick an attribution model and stick to it", body: "Last-touch is simplest. Multi-touch is more accurate but harder. Consistency > sophistication." },
      { title: "Build a dashboard updated weekly", body: "Google Sheets is fine. Channel × spend × revenue × ROI × notes." },
      { title: "Add LTV, not just first-sale revenue", body: "A $50 customer who returns 10x is worth $500. ROI without LTV punishes paid channels." },
      { title: "Make budget decisions monthly", body: "Reallocate from negative-ROI channels to positive ones." },
    ],
    [
      { q: "What's a good marketing ROI?", a: "3:1 (200% ROI) is healthy. Below 1:1 = stop spending. Above 5:1 = scale up." },
      { q: "How do I track offline channels?", a: "Unique phone numbers, coupon codes, or in-checkout surveys." },
      { q: "Should I include my own time?", a: "Yes, at your hourly rate. Otherwise content looks artificially free." },
      { q: "What about brand awareness?", a: "Track separately — brand isn't direct ROI, but it lifts every other channel." },
      { q: "When should I expect ROI?", a: "Search ads: same month. SEO/content: 6–12 months. Brand: 12+." },
    ],
  ),
  mk(
    "how-to-track-where-customers-come-from",
    "Analytics & growth",
    "How to track where customers come from (UTMs, surveys, coupons)",
    "How to track where customers come from",
    "Three layered methods that together capture 80%+ of true source attribution.",
    8,
    "Beginner",
    [
      "Why one tracking method is never enough",
      "How to build clean UTM links",
      "The single survey question that works",
      "Coupon code conventions that don't break",
    ],
    ["A website with analytics", "A way to ask customers at checkout"],
    "No single method captures everything. Layer three and you'll know the truth.",
    [
      { title: "Add UTM parameters to every external link", body: "utm_source, utm_medium, utm_campaign. Google's Campaign URL Builder makes them." },
      { title: "Standardize naming", body: "Lowercase, no spaces, consistent. 'instagram' not 'Instagram' or 'IG'. A messy convention ruins data." },
      { title: "Add a 'How did you hear about us?' question at checkout", body: "Single dropdown with 6 options. Captures offline and word-of-mouth that UTMs miss." },
      { title: "Use unique coupon codes per channel", body: "SUMMER20-IG, SUMMER20-FB, SUMMER20-EMAIL. Track redemptions." },
      { title: "Set up a single dashboard", body: "Google Analytics 4 + your checkout survey + coupon report. Reconcile monthly." },
      { title: "Reconcile the three sources monthly", body: "Each has blind spots. Combined, they paint the picture." },
      { title: "Act on the data", body: "Cut sources that don't appear in any layer. Scale ones that show up in all three." },
    ],
    [
      { q: "Does GA4 do this automatically?", a: "Partially — UTM-based attribution yes, offline no." },
      { q: "What about iOS 14+ tracking changes?", a: "Browser data is less reliable now. Lean more on self-reported and coupons." },
      { q: "How long should I track per campaign?", a: "Minimum 30 days for direct response, 90+ for content and brand." },
      { q: "What's a dark social?", a: "Traffic from DMs, copied links, etc. that has no referrer. Surveys are the only way to catch it." },
      { q: "Cookie-based vs. server-side?", a: "Server-side is more reliable but more setup. Start cookie-based; upgrade if you scale." },
    ],
  ),
  mk(
    "how-to-calculate-customer-lifetime-value",
    "Analytics & growth",
    "How to calculate customer lifetime value (LTV) — simple formula",
    "How to calculate customer lifetime value",
    "Three ways to calculate LTV, when to use each, and how to use it to set your max CAC.",
    8,
    "Intermediate",
    [
      "The simple, advanced, and predictive LTV formulas",
      "Why LTV > 3x CAC is the rule of thumb",
      "How to segment LTV by cohort",
      "Common LTV mistakes",
    ],
    ["12+ months of order data", "A spreadsheet"],
    "LTV is the most-cited and most-misunderstood metric in marketing. Here's how to calculate yours simply and use it for real decisions.",
    [
      { title: "Start with the simple formula", body: "LTV = average order value × purchases per year × years retained. For a $40 AOV, 4x/year, 3-year retention = $480." },
      { title: "Add gross margin for true LTV", body: "Multiply by gross margin %. A 60%-margin business with $480 revenue LTV has $288 LTV." },
      { title: "Calculate by cohort", body: "Group customers by acquisition month. Compare retention curves. The first cohort behavior is often misleading." },
      { title: "Compare LTV to CAC", body: "Healthy: LTV ≥ 3x CAC. Below 1x = unsustainable. Above 5x = under-investing in growth." },
      { title: "Recalculate quarterly", body: "Retention, AOV, and frequency drift. Stale LTV = bad decisions." },
      { title: "Don't use lifetime forever", body: "Cap at 3–5 years. Predicting beyond that is fiction." },
      { title: "Segment by channel and product", body: "Customers from email may have 2x the LTV of customers from paid social. Reallocate spend accordingly." },
    ],
    [
      { q: "What's a good LTV?", a: "Depends on industry, but LTV / CAC of 3:1+ is the universal benchmark." },
      { q: "Should I use revenue or profit?", a: "Profit (gross margin). Revenue LTV overstates the picture." },
      { q: "How many months of data do I need?", a: "12 minimum, 24 ideal." },
      { q: "Do I include refunds?", a: "Yes — net revenue, not gross." },
      { q: "Is LTV the same as CLV?", a: "Yes — interchangeable terms." },
    ],
  ),
  mk(
    "how-to-set-marketing-goals-that-work",
    "Analytics & growth",
    "How to set marketing goals that actually work",
    "How to set marketing goals that work",
    "Move past 'increase awareness' to SMART goals tied to revenue, with a quarterly review rhythm.",
    7,
    "Beginner",
    [
      "Why most marketing goals fail",
      "The SMART framework (with examples)",
      "Leading vs. lagging indicators",
      "Building a quarterly review cadence",
    ],
    ["12 months of baseline data", "A planning meeting block"],
    "Goals that aren't measurable are wishes. Here's a small-business-friendly system that takes 90 minutes a quarter.",
    [
      { title: "Start with revenue", body: "What's the company revenue target this quarter? Marketing goals must roll up to that." },
      { title: "Convert revenue into volume", body: "If revenue target is $100K and AOV is $50, you need 2,000 orders. If close rate is 10%, you need 20,000 leads." },
      { title: "Set 3 SMART goals max", body: "Specific, Measurable, Achievable, Relevant, Time-bound. More than 3 = no focus." },
      { title: "Pick leading indicators", body: "Email signups predict sales. Website visits don't always. Track inputs you can control." },
      { title: "Build a weekly scorecard", body: "5–7 numbers reviewed every Monday. Quick gut check on trajectory." },
      { title: "Hold a 90-minute quarterly review", body: "What hit, what missed, what's next. Set Q+1 goals before Q ends." },
      { title: "Kill goals that no longer matter", body: "If the world changed, the goal should too. Sunk-cost is poison." },
    ],
    [
      { q: "How many goals is too many?", a: "More than 3 quarterly goals = nothing gets done." },
      { q: "Annual or quarterly?", a: "Set annual direction, quarterly action." },
      { q: "What if I miss?", a: "Review honestly. Were the goals wrong, the execution off, or the world unexpected?" },
      { q: "Should I share goals publicly?", a: "Internal yes; external rarely — competitors notice." },
      { q: "Best framework?", a: "OKRs work for teams; SMART for solo founders." },
    ],
  ),
  mk(
    "how-to-a-b-test-marketing-campaigns",
    "Analytics & growth",
    "How to A/B test marketing campaigns (without a statistician)",
    "How to A/B test marketing campaigns",
    "Setup, sample size, and reading results — explained for small businesses with small lists.",
    9,
    "Intermediate",
    [
      "Why most small businesses A/B test wrong",
      "Sample size 101 (calculators included)",
      "What to test (and what not to)",
      "Reading results without fooling yourself",
    ],
    ["A list or audience large enough for splits", "A testing tool or manual split"],
    "Most A/B tests at small scale are noise. Done right, they're the closest thing to free intelligence. Here's how to do them honestly.",
    [
      { title: "Pick one element to test", body: "Subject line OR CTA OR image — never multiple at once. Multivariate needs huge samples." },
      { title: "Calculate sample size first", body: "Use a free calculator (Evan Miller, Optimizely). Most subject-line tests need 1,000+ per arm to detect a 10% lift." },
      { title: "Run for a full cycle", body: "Email tests: minimum 24 hours. Ad tests: at least 7 days to account for day-of-week effects." },
      { title: "Don't peek and stop early", body: "Early 'winners' often regress. Wait for the calculated sample." },
      { title: "Calculate statistical significance", body: "Aim for 95% confidence. Below that = inconclusive, not 'winner'." },
      { title: "Implement winners and retest", body: "Test → implement → re-baseline → test again. Compounding lifts beat one-off wins." },
      { title: "Log every test", body: "What, when, result. After 12 months you'll have a playbook." },
    ],
    [
      { q: "How small a list can A/B test?", a: "Below 500 per arm, results are usually noise. Test bigger things less often." },
      { q: "Best free calculator?", a: "Evan Miller's A/B test calculator." },
      { q: "What if I have no significant result?", a: "Often correct — they're equal. Pick the simpler version and move on." },
      { q: "Can I test pricing?", a: "Carefully — and never on customers who'd compare prices." },
      { q: "How long between tests?", a: "Run one at a time. Overlapping tests confound each other." },
    ],
  ),
  mk(
    "how-to-build-a-marketing-funnel",
    "Analytics & growth",
    "How to build a marketing funnel (TOFU/MOFU/BOFU for small business)",
    "How to build a marketing funnel",
    "Design a funnel that moves strangers to customers — and know exactly where prospects drop off.",
    10,
    "Intermediate",
    [
      "Top/middle/bottom of funnel: what belongs where",
      "Content per funnel stage",
      "Measuring drop-off",
      "Optimizing the leakiest stage first",
    ],
    ["A product or service with a known sales process", "Analytics on each step"],
    "A funnel isn't an aesthetic — it's a tool for finding where you're losing money. Built once, it pays forever.",
    [
      { title: "Map your current customer journey", body: "Awareness → consideration → decision → retention → referral. Write down every touchpoint." },
      { title: "Identify content per stage", body: "TOFU = educational (blog, social). MOFU = comparison (case studies, demos). BOFU = trust (testimonials, free trial)." },
      { title: "Build conversion events for each stage", body: "Email signup, demo request, first purchase, repeat purchase. Track in analytics." },
      { title: "Measure stage-to-stage conversion rates", body: "100 visitors → 20 leads (20%) → 4 customers (20%) → 2 repeats (50%). Find the leak." },
      { title: "Optimize the leakiest stage first", body: "Don't optimize traffic if conversion is the issue. Pareto applies." },
      { title: "Build a retention loop", body: "Repeat customers fund acquisition. Email sequences, loyalty, referrals." },
      { title: "Review and refine quarterly", body: "Stages and content needs evolve. Refresh per quarter." },
    ],
    [
      { q: "Is the funnel dead?", a: "The metaphor's lazy but the math still works. Customers do move through stages." },
      { q: "How many stages should I have?", a: "3–5. More than 7 = you're overthinking." },
      { q: "Where do most leaks happen?", a: "Usually middle (consideration) — the boring stage everyone skips." },
      { q: "Do I need separate content per stage?", a: "Yes — same content rarely works across stages." },
      { q: "What tools help?", a: "GA4 for measurement, HubSpot or ConvertKit for nurture, a notebook for thinking." },
    ],
  ),
];

// ---------- EXPORTS ----------
export const GUIDES: Guide[] = [
  ...REVIEWS,
  ...SOCIAL_SETUP,
  ...CONTENT,
  ...ACQUISITION,
  ...ANALYTICS,
];

export function getGuide(slug: string): Guide | undefined {
  return GUIDES.find((g) => g.slug === slug);
}

export function groupByCategory(): Record<string, Guide[]> {
  return GUIDES.reduce<Record<string, Guide[]>>((acc, g) => {
    (acc[g.category] = acc[g.category] || []).push(g);
    return acc;
  }, {});
}
