export type CommunityCategory = "creator" | "food" | "service";

export interface CommunityFAQ {
  question: string;
  answer: string;
}

export interface CommunityCampaignExample {
  name: string;
  description: string;
  perk: string;
}

export interface CommunityFeature {
  title: string;
  description: string;
}

export interface Community {
  slug: string;
  niche: string;
  nicheSingular: string;
  category: CommunityCategory;
  hook: string;
  h1: string;
  heroPain: string;
  heroSubhead: string;
  builtForIntro: string;
  builtFor: CommunityFeature[];
  campaigns: CommunityCampaignExample[];
  unfairAdvantageIntro: string;
  unfairAdvantage: CommunityFeature[];
  faqs: CommunityFAQ[];
  quickStart: string[];
}

export const COMMUNITIES: Community[] = [
  {
    slug: "yoga-teachers",
    niche: "yoga teachers",
    nicheSingular: "yoga teacher",
    category: "creator",
    hook: "Turn students into your marketing team.",
    h1: "For yoga teachers: turn students into your marketing team",
    heroPain: "You're teaching six classes a week, building a private client list, and the only marketing you have time for is the occasional Instagram story between sun salutations. Social Perks fixes that.",
    heroSubhead: "Students earn class credits, retreat discounts, and private session perks every time they post about your classes. You teach. They market. Everyone wins.",
    builtForIntro: "Yoga teachers don't run businesses like restaurants or retail. Your customer journey is intimate, your community is tight, and your students already love sharing their practice. Social Perks is built around how yoga actually gets discovered.",
    builtFor: [
      { title: "Studio-friendly perk types", description: "Class credits, drop-in passes, workshop discounts, retreat deposits, private session vouchers, mat and prop rewards. Every perk maps to something you already offer — no fake gift cards required." },
      { title: "Post-class moment capture", description: "We send a one-tap text 30 minutes after class ends asking students to share. That's when the endorphins are highest and they're most likely to post. Built-in timing windows you control per class type." },
      { title: "FTC #ad compliance baked in", description: "Wellness FTC enforcement has tightened. Every post students publish through Social Perks automatically includes proper #ad and #partnership disclosures, so neither of you has compliance risk." },
      { title: "Retreat and workshop boosting", description: "Run dedicated campaigns for retreats, immersions, and teacher trainings. Higher-value perks (50% off retreat, free workshop seat) tied to higher-effort posts (Reels, blog reviews, IG carousels)." },
      { title: "Solo-teacher pricing", description: "$49/month flat. No per-student fees. Yoga teachers running their own list shouldn't pay enterprise pricing for a tool designed for them." },
    ],
    campaigns: [
      { name: "Story share for $5 credit", description: "Student posts an Instagram story tagging your studio after any class.", perk: "$5 toward their next class" },
      { name: "Reel review for free class", description: "Student records a 15-second Reel about their experience in a workshop.", perk: "One free drop-in class" },
      { name: "Retreat carousel for $100 off", description: "Past retreatants post a carousel about their experience to promote the next one.", perk: "$100 off the next retreat" },
      { name: "Google review for private session discount", description: "Long-time student leaves a thoughtful Google review.", perk: "25% off a private session" },
      { name: "Teacher training share for $250 off", description: "Past trainees post about their TT experience to attract new applicants.", perk: "$250 off any future training or CE" },
    ],
    unfairAdvantageIntro: "Yoga students post for free already. What changes when you give them a structured reason to do it consistently:",
    unfairAdvantage: [
      { title: "Practice culture is post culture", description: "Yoga students already photograph their mats, post inversions, and tag their teachers. You're not asking them to do something new — you're rewarding behavior they already do." },
      { title: "Identity-affirming content", description: "Posting about yoga signals identity (mindful, healthy, intentional). That makes the post genuine and the reach higher than transactional reviews from other industries." },
      { title: "Long retention, repeat posting", description: "A yoga student stays in your community for years, not weeks. One enrolled student can post 20-40 times over their lifetime, compounding reach." },
    ],
    faqs: [
      { question: "I only have one studio and 60 active students. Is this overkill?", answer: "No — it's actually designed for exactly that. Solo teachers and small studios see better engagement than chains because the community is real. You'll likely activate 30-40 of those 60 students in the first month." },
      { question: "Will my students feel weird being 'paid' to post?", answer: "They won't, because they're not being paid in cash. They're earning practice perks they actually want (free classes, retreat discounts). It feels like a loyalty program, not influencer marketing." },
      { question: "What if a student posts something off-brand?", answer: "Every post goes through an AI review pipeline before earning the perk. You can also set content guidelines (no specific pose claims, no medical advice) that get checked automatically." },
      { question: "Does this work for online classes too?", answer: "Yes. Online students post screenshots, before/after wellness content, and Reels about taking your classes from home. The perk system works identically." },
      { question: "Do I need to handle the FTC #ad disclosure stuff?", answer: "No. Every post auto-injects compliant #ad #partner disclosures per Instagram, TikTok, and FTC guidelines. You don't manage it, your students don't manage it." },
      { question: "Can I run a campaign just for a workshop or retreat?", answer: "Yes. You can have an always-on 'general posting' campaign and layered short-term campaigns for specific offerings. Perks stack or live independently — your choice." },
      { question: "What's the actual setup time?", answer: "About five minutes. You name your studio, set up your first perk (we pre-fill yoga-specific templates), and we generate your QR codes and signup link. Print one QR code, put it at the front desk, you're live." },
    ],
    quickStart: [
      "Sign up and connect your Instagram and Google Business Profile",
      "Pick a starter campaign (we recommend 'Story share for class credit')",
      "Print your QR code and place it at the studio entrance or in your class confirmation email",
      "Mention it once at the end of your next class",
      "Watch your tag count and student credits accumulate in real time",
    ],
  },
  {
    slug: "personal-trainers",
    niche: "personal trainers",
    nicheSingular: "personal trainer",
    category: "creator",
    hook: "Get clients posting about your workouts.",
    h1: "For personal trainers: get clients posting about your workouts",
    heroPain: "You transform bodies for a living and your clients have the receipts — but their transformation photos sit in your camera roll instead of bringing you new clients. Social Perks fixes that.",
    heroSubhead: "Clients earn free sessions, programming discounts, and supplement credits every time they post a workout, a PR, or a progress photo. You coach. They post. Your booking calendar fills.",
    builtForIntro: "PTs operate on word-of-mouth and visual proof. Your clients are walking before-and-afters. Social Perks gives them a reason to share that proof publicly, consistently, and on brand.",
    builtFor: [
      { title: "Progress-photo aware", description: "Built-in privacy controls let clients post body-progress content only on their own feeds (not your studio's) while still earning perks. They keep ownership, you get reach." },
      { title: "Session-based perks", description: "Reward types match how you sell: free sessions, programming month discounts, custom macro plans, supplement credits, gym swag. No awkward dollar-off coupons that don't fit your model." },
      { title: "PR and milestone triggers", description: "Pre-built campaigns fire when clients hit common milestones — first pullup, first 200lb deadlift, 10-week mark, goal weight. They get a celebratory perk, you get a post worth sharing." },
      { title: "Form-check fraud prevention", description: "Every post is verified to be a real workout (not stock content) by our AI review pipeline. You don't pay perks for fake posts." },
      { title: "Gym-floor signage included", description: "QR code posters and locker stickers designed for fitness environments — readable from across a room, durable on metal." },
    ],
    campaigns: [
      { name: "Workout-of-the-day share", description: "Client posts the day's workout to their story tagging you.", perk: "$10 off next package" },
      { name: "PR celebration Reel", description: "Client records a Reel of their personal record lift.", perk: "One free session" },
      { name: "12-week transformation post", description: "Carousel post comparing week 1 vs week 12.", perk: "20% off their next 12-week block" },
      { name: "Google review with photo", description: "Detailed review with one progress photo attached.", perk: "Free macro consultation" },
      { name: "Referral video share", description: "Client tags a friend who could benefit from training in a video post.", perk: "Free session when the friend signs up" },
    ],
    unfairAdvantageIntro: "Why fitness clients are higher-performing posters than almost any other vertical:",
    unfairAdvantage: [
      { title: "Visible results = inherent content", description: "Every PT client is already documenting their progress. Body composition changes, lifts, gym selfies — the content exists. You're just making sure it gets shared with your tag attached." },
      { title: "Aspirational reach", description: "Fitness posts get 2-3x the reach of typical service posts because they trigger aspiration. One client's PR Reel can reach 5,000 people who'd never have heard of you otherwise." },
      { title: "Long-cycle clients, compounding posts", description: "A serious PT client stays for 12-36 months. Twenty posts over that time at average reach beats any paid ad campaign you could afford." },
    ],
    faqs: [
      { question: "My clients are private about their bodies. Will they actually post?", answer: "Privacy concerns are real but smaller than you'd think. We let clients pick non-body-visible post types (lifts, workouts, gear, food) and still earn equivalent perks. Roughly 60% of clients opt in." },
      { question: "I'm a solo trainer, not a gym. Is this for me?", answer: "Especially for you. Solo trainers live or die by referrals. This system turns every client into a recurring referral engine without you having to ask." },
      { question: "What about online coaching clients?", answer: "Online clients are some of the best posters because they're already used to documenting workouts and check-ins. The perk system works identically — they post, you ship perks (free programming weeks, etc.)." },
      { question: "How do I prevent clients from sharing my proprietary programs?", answer: "Set content guardrails in the dashboard. Clients can post that they trained, what they hit, and their results — without exposing specific exercise sequences or programming structure." },
      { question: "Will this conflict with my gym's social media policy?", answer: "Posts are on client accounts, not yours, so most gym policies don't apply. If you train at a commercial gym, this is actually how you build a list that isn't tied to that gym." },
      { question: "Can I exclude clients I don't want representing my brand publicly?", answer: "Yes. The perk program is opt-in and you control who gets the signup link. Many trainers only invite clients who've been with them 90+ days." },
      { question: "What happens when a client churns?", answer: "Unredeemed perks stay valid for 90 days after their last session — giving them a built-in reason to come back. Win-back rates with this feature are around 22%." },
    ],
    quickStart: [
      "Sign up and connect Instagram and your Google Business Profile",
      "Pick the 'PR celebration Reel' starter campaign — fastest activation",
      "Send the perk signup link in your client onboarding email or after their first session",
      "Print one gym-floor QR poster",
      "Track posts, redemptions, and new leads in your dashboard daily",
    ],
  },
  {
    slug: "estheticians",
    niche: "estheticians",
    nicheSingular: "esthetician",
    category: "creator",
    hook: "Turn glow-ups into Instagram content.",
    h1: "For estheticians: turn glow-ups into Instagram content",
    heroPain: "Your clients leave glowing — literally — and that glow is the best advertising you'll ever have. But they go home, take a selfie for themselves, and never tag you. Social Perks fixes that.",
    heroSubhead: "Clients earn facial discounts, product credits, and treatment upgrades every time they post a post-treatment glow shot, a Reel, or a review. You treat. They post. Your books stay full.",
    builtForIntro: "Skincare is a visual industry where 'before and after' is everything. Your treatments produce immediate visible results — the trick is making sure those results live on Instagram, not just in a bathroom mirror.",
    builtFor: [
      { title: "Post-treatment timing", description: "Glow-shot perks fire 2-4 hours after appointment end — long enough for redness to subside, short enough that the glow is still peaking. Built-in scheduling for facials, peels, microneedling, dermaplaning, and lash work." },
      { title: "Skin-condition-aware campaigns", description: "Different campaigns for different services. Acne client posting 90-day progress earns a different perk than a HydraFacial client posting a same-day glow shot. The system maps perk-to-service automatically." },
      { title: "Product credit integration", description: "Earned perks can apply to retail product purchases (serums, cleansers), not just treatments. Pushes retail attach rate alongside service rebookings." },
      { title: "Compliant before-and-after handling", description: "Built-in disclosure templates for medical aesthetics. If you do anything that touches medical-grade (lasers, injectables in scope), the system enforces correct compliance language." },
      { title: "Multi-location ready", description: "If you run a small studio with two-three estheticians, perks attribute to the specific provider, so the client posts about the right person — and you can run per-esthetician leaderboards." },
    ],
    campaigns: [
      { name: "Same-day glow shot story", description: "Client posts a glow-shot selfie tagging the studio within 24 hours.", perk: "$10 off next facial" },
      { name: "Acne 90-day transformation", description: "Carousel comparing skin at intake vs 90 days into a clearing protocol.", perk: "Free LED add-on for life" },
      { name: "Product haul Reel", description: "Client unboxes/reviews retail products purchased at appointment.", perk: "15% off next retail order" },
      { name: "Lash extension fresh-set Reel", description: "Client records a close-up Reel of a fresh set of lashes.", perk: "$25 off their next fill" },
      { name: "Detailed review on Google + Yelp", description: "Long-form review on both platforms within two weeks of appointment.", perk: "Free dermaplane add-on next visit" },
    ],
    unfairAdvantageIntro: "Why your clients post more than other service-business clients:",
    unfairAdvantage: [
      { title: "Selfie default behavior", description: "Skincare clients already take post-appointment selfies as a personal record. You're just giving them a structured reason to share what they were going to take anyway." },
      { title: "Visible immediate result", description: "Unlike a haircut that gets washed in three days, post-facial glow is its own filter. The content is naturally compelling and gets high engagement without effort." },
      { title: "Skincare-curious audience", description: "Your clients' followers are disproportionately interested in skincare. Their posts reach exactly the kind of person likely to book with you. Higher conversion per impression than almost any vertical." },
    ],
    faqs: [
      { question: "My clients don't want to post bare-faced selfies. What can they do instead?", answer: "Lots of options: product flat-lays, treatment room shots, before-with-mask-after-without sequences, voiceover Reels with no face. Each non-face post type still earns perks." },
      { question: "I do medical-grade work. Is the compliance handled?", answer: "Yes. The system enforces non-medical claims language, requires disclaimers on injectable and laser content, and blocks before/afters that violate platform policy. You can also require pre-approval on medical-grade posts before perks unlock." },
      { question: "What about NDAs for executive clients?", answer: "You can flag specific clients as private/no-perk so they're never in the program. They can still tip etc.; they're just outside the public posting flow." },
      { question: "Will it help with retail sales or just bookings?", answer: "Both. Retail-focused campaigns (product haul Reels, product-review posts) drive measurable attach rate increases. Estheticians using retail campaigns see roughly 18-30% retail revenue lift." },
      { question: "Can I tier perks by VIP status?", answer: "Yes. VIPs and long-time clients can have a higher-value perk track. New clients get the entry-level perks." },
      { question: "How do I get clients to sign up at the appointment?", answer: "Most estheticians put a QR code on the treatment-room mirror and on the checkout-counter card reader. Mentioning it once during product recommendation at the end of the session converts about 60%." },
      { question: "Does it integrate with my booking system?", answer: "Square, Vagaro, Mindbody, and Boulevard integrate directly. For others, perks can be redeemed via simple code at checkout." },
    ],
    quickStart: [
      "Sign up and connect Instagram, Google, and your booking system",
      "Pick the 'Same-day glow shot' starter campaign",
      "Add the perk signup QR code to your treatment-room mirror",
      "Mention it during retail recommendation at the end of your next 5 appointments",
      "Watch posts, retail attach, and rebookings in real time",
    ],
  },
  {
    slug: "tattoo-artists",
    niche: "tattoo artists",
    nicheSingular: "tattoo artist",
    category: "creator",
    hook: "Every piece is a portfolio post waiting to happen.",
    h1: "For tattoo artists: every piece is a portfolio post waiting to happen",
    heroPain: "You spent six hours on a sleeve. Your client posted a blurry mirror selfie of it to their close friends story and never tagged you. Social Perks fixes that.",
    heroSubhead: "Clients earn touch-up credits, flash discounts, and merch every time they post a properly-lit photo, a healed shot, or a review. You tattoo. They post. Your DMs fill with consults.",
    builtForIntro: "Tattoo artists are 100% portfolio-driven. Every booked client found you on Instagram. The difference between a busy artist and a slow one is how often quality photos of your work end up on the explore page.",
    builtFor: [
      { title: "Fresh-vs-healed dual campaigns", description: "Two perk tracks per piece — one for fresh shots (24 hours post) and one for healed shots (2-4 weeks post). Healed-shot content is the most credible portfolio content you can have, and most clients forget. We remind them automatically." },
      { title: "Style-specific perk routing", description: "Set different perks per style — fine line, traditional, blackwork, color realism. Bigger pieces unlock bigger perks. A full back-piece collector gets a different reward tier than a flash walk-in." },
      { title: "Touch-up and flash credit perks", description: "Native perk types matching how you operate: free touch-ups, flash-day discounts, gift card to your apparel line, priority booking windows for upcoming guest spots." },
      { title: "Convention and guest-spot mode", description: "Spin up a temporary campaign for a guest spot or convention. Out-of-town clients post tagged content, earn perks usable at your home shop or via shipping." },
      { title: "Apprentice-friendly", description: "Two-tier shop accounts — head artist gets full controls, apprentice gets their own campaigns and analytics. Builds their portfolio without dilution." },
    ],
    campaigns: [
      { name: "Fresh-piece feed post", description: "Client posts a well-lit feed photo within 48 hours tagging you and the shop.", perk: "$25 off next session or free touch-up" },
      { name: "Healed-shot return", description: "Client posts a 3-week healed shot demonstrating final settling.", perk: "10% off their next piece" },
      { name: "Time-lapse Reel from your video", description: "Client posts your time-lapse with a caption about the experience.", perk: "Free flash piece up to 3 inches" },
      { name: "Convention shoutout", description: "Convention client posts about their travel-piece while you're still at the event.", perk: "Priority booking for your next guest spot in their city" },
      { name: "Big-piece carousel review", description: "Major piece collector posts a multi-image carousel with a written review.", perk: "20% off the next session in the series" },
    ],
    unfairAdvantageIntro: "No vertical produces better organic content than tattooing. Here's why:",
    unfairAdvantage: [
      { title: "The piece IS the content", description: "Other businesses need their customers to film something. You give your customers permanent content that they will photograph for the rest of their lives. Every shower selfie is a portfolio post." },
      { title: "Identity-defining purchase", description: "Tattoos are among the highest-identity-signal purchases anyone makes. Clients are deeply motivated to share, credit the artist, and engage with the post over time." },
      { title: "Algorithm-favored content", description: "Tattoo content performs exceptionally well across IG and TikTok. Process Reels, reveal moments, and healed-shot reveals routinely break 100k views. One post can fill a booking calendar for months." },
    ],
    faqs: [
      { question: "Most of my clients are already posting. Why pay for this?", answer: "They post some, not most, and rarely with good lighting or your tag in the right spot. Structured perks raise the share rate from ~25% to ~70% and improve photo quality measurably. The healed-shot capture alone is worth it." },
      { question: "What about clients with private accounts?", answer: "Private-account posts still count if tagged correctly — we verify via the platform API. Perk gets issued, you just don't get the public reach. Many shops still want them in the program for retention." },
      { question: "Can I exclude specific clients?", answer: "Yes — the program is opt-in and you control the signup link. Many artists only offer it to repeat collectors, not walk-ins." },
      { question: "Does it work for cover-ups and progress pieces?", answer: "Yes. Big multi-session pieces have a per-session campaign and a big 'completion' campaign that unlocks a larger reward when finished and shared." },
      { question: "What about FTC and disclosure?", answer: "Auto-injected on every post. Both platforms require it now and we handle the wording per platform." },
      { question: "Will my apprentice's posts compete with mine?", answer: "No — apprentices have their own campaigns and you can route shop tag and apprentice tag separately. Their portfolio grows under their own name on your shop's roof." },
      { question: "I do appointments via email/DMs only. Does this still fit?", answer: "Yes. The signup link goes in your booking confirmation email, your IG bio, or the consent form clients sign before the session." },
    ],
    quickStart: [
      "Sign up and connect Instagram",
      "Set up the 'Fresh-piece feed post' campaign as your default",
      "Add the perk signup link to your booking confirmation email and IG bio",
      "Hand a small card with the QR code to clients during aftercare instructions",
      "Watch portfolio reach and inbound DMs climb in your dashboard",
    ],
  },
  {
    slug: "nail-techs",
    niche: "nail technicians",
    nicheSingular: "nail technician",
    category: "creator",
    hook: "Every set is content.",
    h1: "For nail technicians: every set is content",
    heroPain: "You did a full chrome french with hand-painted detail. Your client posted it to her close friends story. Eight people saw it. Social Perks fixes that.",
    heroSubhead: "Clients earn fill discounts, free art add-ons, and product credits every time they post a fresh set, a Reel, or a review. You build sets. They post. Your books fill weeks out.",
    builtForIntro: "Nail art is a fundamentally photo-driven craft. Clients book based on what they see on Instagram and TikTok. Your job is to make sure every set you do ends up on those platforms tagged to you.",
    builtFor: [
      { title: "Fresh-set post timing", description: "Auto-prompts go out within 4 hours of appointment end — when nails are freshly buffed, photographed well in natural light, and most likely to be posted." },
      { title: "Set-type campaigns", description: "Different perks per service: structured manicure, builder gel, acrylic, dip, hand-painted art, chrome, jelly, gel-x. Bigger artistry, bigger perk." },
      { title: "Photo-quality nudge", description: "Built-in lighting and angle tips delivered with the post prompt — your clients deliver more usable content when they post and it brings you more bookings." },
      { title: "Fill-day perk loops", description: "Specific 'fill day' campaigns reward clients for returning posts every 2-3 weeks. Builds an evergreen content stream and locks in fill cadence." },
      { title: "Booth-renter friendly", description: "Designed for solo booth renters and small studios. No per-employee fees, no enterprise overhead — flat $49/month for one nail tech." },
    ],
    campaigns: [
      { name: "Fresh set story tag", description: "Client posts a story photo of the new set within 24 hours.", perk: "$5 off next fill" },
      { name: "Nail art Reel", description: "Client records a Reel showing off intricate art or chrome work.", perk: "One free art add-on next visit" },
      { name: "Fill-day repeat post", description: "Same client posts at every fill for 3 months straight.", perk: "Free 3-month service at month 4" },
      { name: "Holiday/season set carousel", description: "Multi-image post showcasing themed holiday or season set.", perk: "$15 off their next themed set" },
      { name: "Detailed Google review", description: "Long thoughtful review posted within 7 days.", perk: "Free upgrade to gel polish on next mani" },
    ],
    unfairAdvantageIntro: "Why nail clients are among the most reliable posters in any service business:",
    unfairAdvantage: [
      { title: "Fresh-set photo is muscle memory", description: "Every client has taken a fresh-set photo for themselves already. Adding a tag and a perk takes zero effort on their part — they're not creating new content, they're just publishing what they already made." },
      { title: "Recurring service = recurring posts", description: "Most clients fill every 2-3 weeks, meaning each active client posts 17-26 times a year. No other service business gets that volume from a single customer." },
      { title: "Tagging culture is normative", description: "It's industry norm to credit your nail tech publicly. Your clients already know the etiquette. The perk just makes them do it consistently and well." },
    ],
    faqs: [
      { question: "I'm a solo booth renter. Will this work without a salon?", answer: "Perfect fit. The platform is designed for solo techs and small studios. You don't need a salon brand — your personal handle is the brand." },
      { question: "What if my client never tags me even with the perk?", answer: "Tagging is the requirement for perk redemption — no tag, no perk. We verify automatically. Untagged posts simply don't unlock the reward." },
      { question: "Can I require specific hashtags for the studio's content series?", answer: "Yes. You can require up to 3 hashtags per campaign — your handle, a brand hashtag, and a campaign hashtag if you run a content series." },
      { question: "Does it work for TikTok-first clients?", answer: "Yes. TikTok is fully supported and many techs find TikTok performs even better than Instagram for nail content." },
      { question: "Can I run flash sales for specific weeks?", answer: "Yes. Time-limited campaigns are built in. Run a 'February gel-x flash week' with elevated perks, then revert to your defaults." },
      { question: "What happens if a client doesn't redeem their perk?", answer: "Perks stay valid for 90 days, then expire (you set the window). Expiry rates run around 30-40% — saving you redemption cost while still motivating posting." },
      { question: "How do I track which campaign brought me the most new clients?", answer: "Every campaign has attribution analytics. You'll see posts, reach, conversion-to-booking, and revenue tied back to the original perk." },
    ],
    quickStart: [
      "Sign up and connect Instagram and TikTok",
      "Pick the 'Fresh set story tag' starter campaign",
      "Add the perk signup link to your IG bio and booking confirmation",
      "Mention it once during your next 5 client checkouts",
      "Watch tags, reach, and bookings grow weekly in your dashboard",
    ],
  },
  {
    slug: "food-truck-operators",
    niche: "food truck owners",
    nicheSingular: "food truck owner",
    category: "food",
    hook: "Location-based marketing on autopilot.",
    h1: "For food truck owners: location-based marketing on autopilot",
    heroPain: "You parked at the brewery on Saturday and 200 people ate your tacos. Three posted. The next week you're at a different spot and nobody knows where you are. Social Perks fixes that.",
    heroSubhead: "Customers earn $2 off, free upgrades, and merch every time they post your location, your menu, or your truck. You cook. They post. The next location fills before you even park.",
    builtForIntro: "Food truck marketing has one job: tell people where you'll be next. Social Perks turns every customer into a location announcer — and pays them in tacos to do it.",
    builtFor: [
      { title: "Location-of-the-day campaigns", description: "Each parking location is its own campaign. Customers post the location, you build a real-time follower count for that spot, and you know which spots produce the best ROI." },
      { title: "Lightweight perk redemption", description: "Customers redeem via 4-digit code at the window — no app required. Stripe and Square integration takes the discount off the next order. Works in 5 seconds in a moving line." },
      { title: "Menu-item-specific perks", description: "Run campaigns like 'post a Reel of our birria taco, get a free agua fresca.' Drives specific menu items, not just generic discounts." },
      { title: "Event and festival mode", description: "Temporary high-volume campaigns for festivals, fairs, and special events. Higher-value perks, location-specific, time-limited." },
      { title: "Weather-aware re-engagement", description: "Slow rainy day at your usual lunch spot? Push a 'post-now-eat-now' flash perk to your list — boost foot traffic in under an hour." },
    ],
    campaigns: [
      { name: "Location story share", description: "Customer posts a story showing the truck at the day's location.", perk: "$2 off their order today" },
      { name: "Order unboxing Reel", description: "Customer posts a Reel opening their order at the truck or nearby.", perk: "Free agua fresca on next visit" },
      { name: "Menu item carousel", description: "Carousel showing multiple menu items they got.", perk: "Free side on next order" },
      { name: "Festival post + tag", description: "Tag the truck at a festival or event the truck is working.", perk: "Free upgrade to combo at the event" },
      { name: "Google review with truck photo", description: "Google review including a photo of the truck or food.", perk: "Free taco on next visit (within 30 days)" },
    ],
    unfairAdvantageIntro: "Food truck customers post at 3x the rate of restaurant customers. Here's why:",
    unfairAdvantage: [
      { title: "Location urgency drives shares", description: "When you tell someone where to find delicious food at a specific brewery TODAY, they share it because it's useful information. That's a different post type than a generic restaurant review — and it converts." },
      { title: "Visual food + outdoor setting", description: "Food truck content (food + truck + outdoor lighting + line of people) is some of the highest-performing food content on the algorithm. One Reel routinely outperforms a month of restaurant posts." },
      { title: "Community discovery", description: "Truck customers are usually locals who follow other locals. A post about your taco truck reaches the exact 200 people most likely to come find you tomorrow." },
    ],
    faqs: [
      { question: "I park at 4 different spots a week. Does it handle that?", answer: "Yes — each spot can be its own location campaign, or you can use a single 'wherever we are' campaign that pulls from your current location. Most operators use a hybrid." },
      { question: "How do customers know there's a perk?", answer: "Static QR codes on the truck wrap, the menu board, and the receipt. Plus, mentioning it once when you hand over the food converts roughly 40% of customers to opt in." },
      { question: "What about my regulars who already post?", answer: "Regulars are your best perk redeemers. Once enrolled, they post more often AND post higher-quality content because they know it's earning them perks." },
      { question: "Does the redemption slow down my line?", answer: "No. Codes are entered like a coupon at checkout. About 3-4 seconds added per redemption — less than a card-vs-cash decision." },
      { question: "Can I limit redemptions per customer per visit?", answer: "Yes. Default is one perk per visit and you can adjust per campaign. Most operators set max 1-2 perks per order." },
      { question: "Do festivals and pop-up events count differently?", answer: "Yes — you can run a special elevated campaign for events. Higher perk values, time-boxed to the event, plus standard always-on campaigns running in parallel." },
      { question: "What if I sell out before someone can redeem?", answer: "Perks roll forward to next visit. We've found this actually drives faster return visits because customers want to use them before they expire (default 30 days for food truck perks)." },
    ],
    quickStart: [
      "Sign up and connect Instagram, TikTok, and your POS",
      "Set up your default 'location story share' campaign",
      "Print one QR code for the order window and one for the receipt",
      "Mention it during your next service window for one shift",
      "Watch posts and location attribution roll in",
    ],
  },
  {
    slug: "craft-brewers",
    niche: "craft brewers",
    nicheSingular: "craft brewer",
    category: "food",
    hook: "Turn tap room visitors into brand evangelists.",
    h1: "For craft brewers: turn tap room visitors into brand evangelists",
    heroPain: "You released a hazy IPA on Saturday and your tap room had a line out the door. Two of those drinkers posted. Now the can's on shelves at a distributor and nobody knows what it tastes like. Social Perks fixes that.",
    heroSubhead: "Drinkers earn free pours, growler discounts, merch, and brewery-tour perks every time they post a flight, a can, or a tap-room photo. You brew. They post. Your can sales lift before they hit the cooler.",
    builtForIntro: "Craft beer lives or dies by enthusiast posts. Untappd reviews, Reels of pours, can-art carousels — they're how the next release gets discovered. Social Perks structures and rewards that posting behavior at the tap room and in the wild.",
    builtFor: [
      { title: "Release-day campaigns", description: "Stand up a dedicated campaign for each new release — different perks for the first 48 hours, the first weekend, and the first month. Concentrates posting bursts when the release matters most." },
      { title: "Untappd-aware integrations", description: "Untappd check-ins count as qualifying posts. Pair with Instagram and you're capturing both your craft-enthusiast audience and your broader visual audience." },
      { title: "Tap-room perk types", description: "Free pour, growler fill discount, brewery merch, mug-club priority slot, brewery-tour seat, bottle-share invite. Native to how brewers actually reward fans." },
      { title: "Distribution-zone tracking", description: "When you start hitting bars and shelves, customers in distribution markets post tagged content — you see exactly where demand is forming. Critical data for which markets to push next." },
      { title: "Compliance-aware (alcohol)", description: "Built-in age-gating for sign-ups (21+) and mandatory drink-responsibly disclosures on posts in regulated states. We track per-state alcohol marketing rules so you don't have to." },
    ],
    campaigns: [
      { name: "Tap-room flight story", description: "Visitor posts a story of a flight at the tap room.", perk: "$3 off a 4-pack" },
      { name: "Release-day Reel", description: "Visitor records a Reel of the new release on opening weekend.", perk: "Free pint on next visit" },
      { name: "Untappd check-in + photo", description: "Check-in with detailed rating and at-bar photo.", perk: "Discounted growler fill" },
      { name: "Out-in-the-wild can post", description: "Customer posts a can or pour from a bar/restaurant — not the tap room.", perk: "10% off next can order at the brewery" },
      { name: "Brewery tour carousel", description: "Tour visitor posts multi-image carousel of the brewing process.", perk: "Mug-club priority slot when next round opens" },
    ],
    unfairAdvantageIntro: "Why craft beer customers are the most engaged poster base in food and beverage:",
    unfairAdvantage: [
      { title: "Enthusiast identity", description: "Craft beer drinkers self-identify as enthusiasts. Posting about beer is part of their identity — they were going to do it whether you rewarded them or not. The perk just makes it consistent." },
      { title: "Discovery-driven follower base", description: "Beer drinkers follow other beer drinkers specifically to discover new releases. A post about your fresh hazy IPA reaches a hyper-targeted audience already primed to buy." },
      { title: "Multi-platform native", description: "Beer culture spans Untappd, Instagram, TikTok, Reddit, and YouTube. Your customers are already cross-posting — you just get credit and reach across all of them." },
    ],
    faqs: [
      { question: "Can I run different campaigns for tap-room vs. retail customers?", answer: "Yes. Tap-room perks redeem at the brewery. Retail-zone customers can earn merch credit or brewery-experience perks (brewery tour, mug club priority) that pull them back to the source." },
      { question: "What about state alcohol marketing rules?", answer: "Built in. The system enforces compliant copy per state, age-gates all signups, and blocks promotion to underage accounts. You don't manage it." },
      { question: "Untappd is critical for us. Does it count?", answer: "Yes. Untappd check-ins are a first-class post type. Both rating-and-photo and detailed reviews count toward perks." },
      { question: "Can mug-club members get a different perk tier?", answer: "Yes. Tiered perk tracks — mug-club, regulars, new customers, distribution-zone customers — each with their own perk structure." },
      { question: "How do I handle non-drinker visitors (designated drivers, kids, food-only)?", answer: "Non-drinker perks (free soda, food upgrade, kid's meal) so the whole table participates. Keeps the social-media circle bigger." },
      { question: "Does this conflict with our distributor relationships?", answer: "No. The perks redeem at your brewery, not at retail. Distributors generally love it because it lifts the brand at on-premise accounts they sell to." },
      { question: "Can I incentivize specific releases more than the flagship?", answer: "Yes. Per-release campaign perk values are configurable. New releases typically get 2-3x flagship perk value during the launch window." },
    ],
    quickStart: [
      "Sign up and connect Instagram, Untappd, and Google",
      "Set up your default 'Tap-room flight story' campaign",
      "Add a QR code to your tap room tables and your tap menu",
      "Hand the bartender team a 30-second pitch to mention to new customers",
      "Stand up a release-day campaign for your next drop and watch enrollment spike",
    ],
  },
  {
    slug: "specialty-coffee-roasters",
    niche: "specialty coffee roasters",
    nicheSingular: "specialty coffee roaster",
    category: "food",
    hook: "Educate, then activate.",
    h1: "For specialty roasters: educate, then activate",
    heroPain: "You're sourcing a microlot from a producer you've worked with for five years. The roast profile is dialed in. The bag art is beautiful. And your customers post pictures of generic 'morning coffee' without mentioning the farm, the process, or you. Social Perks fixes that.",
    heroSubhead: "Customers earn bag discounts, brew gear credits, and cupping-event seats every time they post a bag, a brew, or a tasting note. You roast. They post. Specialty-coffee discovery actually rewards you.",
    builtForIntro: "Specialty coffee is education-led marketing. Your customers want to talk about the farm, the process, the cupping notes — they just need the prompts and the rewards. Social Perks turns coffee education into shareable content with built-in incentives.",
    builtFor: [
      { title: "Origin-aware campaigns", description: "Per-origin campaigns let you push specific microlots. Customers earn elevated perks for posting about a featured Ethiopian or Costa Rican lot during release windows." },
      { title: "Brew-method perk routing", description: "Pour-over post, espresso pull video, AeroPress hack, French press carousel — each method has its own campaign. You build content variety, customers self-select their style." },
      { title: "Subscription-friendly perks", description: "Subscription-bag credits, free gift bag at next renewal, public-cupping seat priority. Native perks that align with how specialty coffee actually retains." },
      { title: "Producer-relationship storytelling", description: "Built-in content prompts to help customers credit producers, not just the roaster. Strengthens your supply-chain story and gets you better PR with your producers." },
      { title: "Cafe partner network", description: "If your beans are wholesaled to cafes, those cafes can run perks attributing back to your roastery — building consumer demand for your label at the cafe counter." },
    ],
    campaigns: [
      { name: "Bag-on-the-shelf flat-lay", description: "Customer posts a flat-lay of the bag with their pour-over setup.", perk: "$3 off next bag" },
      { name: "Brew Reel with origin notes", description: "Customer records a brew video mentioning the farm/process/notes.", perk: "Free 4oz tasting sampler in next order" },
      { name: "Subscription unboxing", description: "Subscriber posts an unboxing Reel of the monthly bag.", perk: "Free shipping on their next renewal" },
      { name: "Public-cupping invitation share", description: "Customer posts about attending a public cupping.", perk: "Priority seat at the next cupping" },
      { name: "Cafe partner pour photo", description: "Customer posts a cafe pour photo tagging both the cafe and the roastery.", perk: "10% off a bag purchase at the roastery" },
    ],
    unfairAdvantageIntro: "Specialty coffee customers post 4-5x more than commodity coffee drinkers. Here's the why:",
    unfairAdvantage: [
      { title: "Identity-driven enthusiasm", description: "Specialty coffee is a deep hobby for your customers. They already photograph their brews, their gear, and their setups. You're just structuring and rewarding that behavior." },
      { title: "Education-as-content advantage", description: "Specialty coffee content is informational, not transactional. It performs better algorithmically than a generic 'I had coffee' post because it teaches something. Your customers love that they look knowledgeable when they post." },
      { title: "Subscription compounding", description: "Specialty customers tend to subscribe and stay. A subscriber posting monthly produces 12+ posts per year per customer. With 200 enrolled subscribers, that's a 2,400-post content engine." },
    ],
    faqs: [
      { question: "I'm a small roastery doing 200 bags a week. Worth it?", answer: "Yes — and especially so. Smaller roasteries can't outspend the big ones, but you can out-engage them. 200 weekly bags activated at even 25% posting rate is 50 posts a week building demand." },
      { question: "Will customers actually mention the farm and process?", answer: "Only if you prompt them. Built-in content prompts (\"include the producer's name\", \"mention process or varietal\") raise origin-credit rate from ~5% to ~60%." },
      { question: "Can I differentiate perks for subscribers vs one-time buyers?", answer: "Yes. Two-tier perk system. Subscribers earn faster and unlock subscriber-only rewards (free monthly bag, private-cupping invites)." },
      { question: "Do cafe customers count if they didn't buy direct?", answer: "Yes. Cafes can be partner accounts. Cafe-pour posts earn customers a discount at the roastery — drives direct sales and strengthens cafe-roaster relationship." },
      { question: "How does it integrate with my Shopify storefront?", answer: "Native Shopify integration. Perks redeem as discount codes at checkout, attribution flows back into your dashboard." },
      { question: "What about wholesale-only roasteries?", answer: "Wholesale-only roasters can still run consumer-facing perks via cafe partnerships and direct subscriptions. Most pure-wholesale roasters use Social Perks to gradually build a direct subscriber base." },
      { question: "Will my producers be happy with this?", answer: "Producers love when roasters drive recognition back to origin. Many roasters share their dashboard data with producers as part of relationship management." },
    ],
    quickStart: [
      "Sign up and connect Instagram and Shopify",
      "Set up your default 'Bag flat-lay' campaign",
      "Print a small card with the QR code, drop it in every order",
      "Email your subscriber list once announcing the program",
      "Run a featured-origin campaign within your first week",
    ],
  },
  {
    slug: "ice-cream-shops",
    niche: "ice cream shops",
    nicheSingular: "ice cream shop",
    category: "food",
    hook: "Every cone is a photo opportunity.",
    h1: "For ice cream shops: every cone is a photo opportunity",
    heroPain: "You scoop 400 cones on a Friday night. Maybe 8 get posted. The rest just get eaten. Social Perks fixes that.",
    heroSubhead: "Customers earn free scoops, flavor-of-the-week previews, and birthday-month perks every time they post a cone, a sundae, or a happy kid licking sprinkles. You scoop. They post. Saturday is even busier.",
    builtForIntro: "Ice cream is the most postable food on the planet. Visual, kid-friendly, weather-driven, line-out-the-door energy. Social Perks turns that natural postability into a structured marketing engine.",
    builtFor: [
      { title: "Kid-and-parent perks", description: "Parents post the kid-with-cone shot, parents earn the perk. Built-in COPPA-aware design — never tracks or markets to children." },
      { title: "Flavor-launch campaigns", description: "New flavor drops every week or month? Stand up a flavor-specific campaign in 30 seconds. Customers post the new flavor, you build instant social proof at launch." },
      { title: "Seasonal perk structure", description: "Summer perks differ from winter perks. Birthday-month freebies, snow-day promos, school-out-for-summer campaigns — all configurable per-season." },
      { title: "Line-of-day moments", description: "Saturday-night line photos are gold — they signal popularity. The system prompts customers in line (via QR code at the door) to post and earn while they wait." },
      { title: "Loyalty card replacement", description: "Replaces punch cards. Customers earn faster by posting AND buying. Drives repeat visits and content simultaneously." },
    ],
    campaigns: [
      { name: "Cone-of-the-day story", description: "Customer posts a story of their cone tagging the shop.", perk: "$1 off next scoop" },
      { name: "Sundae Reel", description: "Customer films a Reel of an elaborate sundae or banana split.", perk: "Free topping on next visit" },
      { name: "Kid-and-cone photo", description: "Parent posts kid happily with their cone, tagged.", perk: "Free kid's scoop next visit" },
      { name: "Flavor launch post", description: "Customer posts the brand-new weekly flavor.", perk: "Free preview scoop on next week's launch" },
      { name: "Birthday-month celebration post", description: "Customer posts about their birthday visit, tagged.", perk: "Free birthday sundae" },
    ],
    unfairAdvantageIntro: "Why ice cream is the highest-converting food category for social-media perks:",
    unfairAdvantage: [
      { title: "Visual perfection by default", description: "Ice cream looks great in every photo. No food styling needed. The cone is its own content." },
      { title: "Emotional content", description: "Ice cream posts trigger nostalgia, family, joy. They perform 2-3x better on engagement than other food posts. The algorithm loves them." },
      { title: "Repeat-visit driver", description: "Ice cream is a habit, not a destination. Once enrolled, a customer visits 5-15 times a season. Each visit is a potential post." },
    ],
    faqs: [
      { question: "We do a high volume of one-time tourists in summer. Is this worth it for them?", answer: "Yes — tourists are some of the best posters because they're already in vacation-post mode. Even one tourist post reaches their hometown network, often hundreds of potential return-visit customers." },
      { question: "How do I handle kids in posts?", answer: "All perks are linked to the adult account. Kids in posts are great content but the perk and the data are 100% with the adult. COPPA-compliant by design." },
      { question: "Can I run a birthday-month freebie automatically?", answer: "Yes. Customers enter birth month at signup, get an automatic perk-redeemable freebie that month if they post a birthday celebration." },
      { question: "What about weather-driven days?", answer: "Push a flash perk on hot Saturdays to enrolled customers in a 10-mile radius. Promo runs for 4 hours, drives same-day traffic. Most shops see 15-30% traffic lift on flash days." },
      { question: "How does it work with our punch-card or loyalty system?", answer: "Replaces or augments. Many shops keep the punch card and add the perk system on top — customers earn faster with both, you get content too." },
      { question: "What if a customer posts something messy or off-brand?", answer: "All posts run through an AI review pipeline before perks unlock. Off-brand or low-quality content gets flagged and held for your review." },
      { question: "Does it work for fro-yo, gelato, frozen custard shops too?", answer: "Yes — all frozen treats. The campaigns and perks are identical." },
    ],
    quickStart: [
      "Sign up and connect Instagram and your POS",
      "Set up the 'Cone-of-the-day story' campaign",
      "Print a QR code for the order counter and one for the dining area",
      "Train scoopers to mention the perk once per shift",
      "Watch your tag count, repeat visits, and weekend lines climb",
    ],
  },
  {
    slug: "food-bloggers",
    niche: "food bloggers",
    nicheSingular: "food blogger",
    category: "food",
    hook: "Monetize your audience with brand perks.",
    h1: "For food bloggers: monetize your audience with brand perks",
    heroPain: "You've grown to 18,000 followers and a healthy email list. Brand deals are slow, sponsored posts feel forced, and your audience would rather have a discount than another #ad. Social Perks fixes that.",
    heroSubhead: "Your readers earn real perks (discounts at restaurants you cover, free product from brands you partner with, exclusive event seats) every time they post about your recommendations. You recommend. They activate. You earn a share.",
    builtForIntro: "Food bloggers are the missing link between brands and engaged audiences. Social Perks lets you monetize your influence directly — your audience gets real perks, brands get measurable activation, and you get a transparent revenue share.",
    builtFor: [
      { title: "Multi-brand perk wallet", description: "Your audience signs up once and gets a wallet of perks across every brand you partner with. They earn perks for posting about ANY brand you've onboarded, not one-off offers." },
      { title: "Transparent revenue share", description: "20% revenue share on perks redeemed from your audience. Tracked transparently, paid monthly. No black-box brand-deal pricing." },
      { title: "Audience-aligned brand matching", description: "We match you with brands fitting your niche (BBQ blogger gets BBQ-sauce brand offers, baking blogger gets flour and butter brand offers). You stay on-brand, audience stays trusting." },
      { title: "FTC-compliant by design", description: "Every audience post auto-tags as paid partnership per FTC rules. No legal exposure for you, no shaky disclosures from your audience." },
      { title: "Newsletter and Substack integration", description: "Embed perk-claim links directly in your newsletter. Readers redeem in one tap — no signup friction." },
    ],
    campaigns: [
      { name: "Restaurant rec activation", description: "Reader visits a restaurant you recommended, posts a tagged photo.", perk: "Free appetizer or 15% off" },
      { name: "Recipe-brand product post", description: "Reader makes a recipe using a brand product you partnered with, posts the result.", perk: "Free product on next order" },
      { name: "Newsletter-exclusive perk drop", description: "Subscribers post a Reel within 72 hours of a recipe drop using a featured brand.", perk: "Exclusive bundle priced for subscribers only" },
      { name: "Event partnership share", description: "Reader attends a food event you're hosting/featuring, posts tagged.", perk: "Free entry to next event or merch" },
      { name: "Cookbook bundle review", description: "Reader posts a review of your cookbook with a featured brand's product.", perk: "Branded prize package" },
    ],
    unfairAdvantageIntro: "Why food-blog audiences convert at higher rates than influencer audiences:",
    unfairAdvantage: [
      { title: "Trust capital from real content", description: "Your audience built up trust over hundreds of recipes. When you say a brand is worth it, they believe you. Influencer audiences don't have that depth." },
      { title: "High-intent at high frequency", description: "Food blog readers come back weekly for new recipes. Each visit is a potential conversion. They're already in 'I'm cooking this' mode, perks just nudge them across." },
      { title: "Email + social hybrid", description: "Your email list is your audience's most engaged channel. Combining newsletter drops with social perks doubles activation versus social-only influencer deals." },
    ],
    faqs: [
      { question: "I already do sponsored posts. How is this different?", answer: "Sponsored posts pay you a one-time fee. Social Perks pays you a share of every redemption from your audience — recurring revenue tied to activation, not a flat post fee. Most bloggers earn more on perks than sponsored posts within 90 days." },
      { question: "What size audience do I need to qualify?", answer: "5,000+ engaged followers across any combination of Instagram, TikTok, Substack, or email list. We weight engagement over raw follower count." },
      { question: "Do I have to take every brand offer?", answer: "No. You approve every brand partnership manually. Decline anything off-brand, your audience never sees it." },
      { question: "How do I get paid?", answer: "Monthly via Stripe Connect. Dashboard shows exactly which posts drove which redemptions and your revenue share in real time." },
      { question: "Can I bring my own brands?", answer: "Yes. If you already have brand relationships, you can onboard them directly to the platform and keep 100% of the relationship (we charge a small flat platform fee instead of taking a revenue share)." },
      { question: "What about audience trust if perks feel salesy?", answer: "Audiences love perks because they're real discounts on things readers were already curious about. They feel meaningfully different from sponsored content. Audience retention actually improves." },
      { question: "Does this conflict with my existing affiliate links?", answer: "No. Affiliate revenue and perk revenue stack. Many bloggers use both, with affiliate for evergreen recommendations and perks for activation drives." },
    ],
    quickStart: [
      "Sign up and connect Instagram, Substack/email, and TikTok",
      "Get matched with 3-5 brand partners in your niche within 24 hours",
      "Approve your first partnership",
      "Drop the perk-claim link in your next newsletter and IG bio",
      "Watch activations, audience growth, and revenue share roll in monthly",
    ],
  },
  {
    slug: "mobile-detailers",
    niche: "mobile auto detailers",
    nicheSingular: "mobile auto detailer",
    category: "service",
    hook: "Before-and-afters are gold.",
    h1: "For mobile auto detailers: before-and-afters are gold",
    heroPain: "You spent 4 hours turning a mud-caked daily driver into a showroom car. The owner thanked you, paid, and drove off. Two before-and-after photos sat on your phone. Social Perks fixes that.",
    heroSubhead: "Clients earn detail discounts, ceramic coat upgrades, and interior protection treatments every time they post your before-and-afters. You detail. They post. Your route fills out two weeks ahead.",
    builtForIntro: "Mobile detailing is a referral business with built-in viral content (before/afters) and yet most detailers never see that content distributed. Social Perks turns every job into a structured marketing event.",
    builtFor: [
      { title: "Before-and-after capture protocol", description: "Two-photo workflow built in: a before shot at intake, an after shot at completion, both timestamped. Customer posts the side-by-side, perk unlocks." },
      { title: "Driveway-job logistics", description: "QR code stickers for the rear window or fuel cap area. Customers see them every day, reminded to post. Designed for mobile workflows, not shop walk-ins." },
      { title: "Ceramic-and-PPF upsell perks", description: "High-end perks (free interior shampoo, $200 off ceramic coating) tied to higher-effort posts (Reels, multi-image carousels) — building demand for premium services." },
      { title: "Route-aware reach analytics", description: "See which neighborhoods produce the most posts and bookings. Optimize your route around your highest-ROI zip codes." },
      { title: "Fleet-client mode", description: "If you service commercial fleets, fleet managers can run perks for their drivers — keeping company vehicles cleaner AND building your social presence in the local commercial market." },
    ],
    campaigns: [
      { name: "Before-and-after carousel", description: "Customer posts a side-by-side comparison post within 24 hours.", perk: "$20 off next detail" },
      { name: "Engine bay or interior Reel", description: "Customer records a Reel showing engine bay or interior detail work.", perk: "Free interior shampoo on next visit" },
      { name: "Ceramic-coat reveal video", description: "Customer posts a water-beading or paint-shine reveal after ceramic coating.", perk: "$100 toward future PPF" },
      { name: "Truck-bed or boat detail", description: "Customer posts an unusual vehicle detail (boat, truck bed, motorcycle).", perk: "Free polish on next service" },
      { name: "Google review with photos", description: "Detailed Google review including before-and-after images.", perk: "Free interior cleaning add-on" },
    ],
    unfairAdvantageIntro: "Why detailing customers are some of the highest-converting posters in service businesses:",
    unfairAdvantage: [
      { title: "Before-and-after is inherently viral", description: "The format wins on every algorithm. A muddy truck turning into a showroom truck triggers the same dopamine as a renovation Reel. One good carousel reaches 10,000+ people regularly." },
      { title: "Car-culture audience", description: "Auto enthusiasts follow other auto enthusiasts. A clean-detail post on your customer's profile reaches a hyper-targeted local audience of likely buyers." },
      { title: "Seasonal cycle", description: "Detailing is repeat business (every 4-8 weeks for serious customers). Each customer can post 6-12 times a year. Compounded across 100 clients, that's 600-1,200 organic posts annually." },
    ],
    faqs: [
      { question: "I'm a one-person operation working out of my truck. Does this fit?", answer: "Perfectly. Mobile solo detailers are the sweet spot for this. No marketing team, customers love the service, and they want to show it off — they just need a system." },
      { question: "How do I get customers to take the before-shot?", answer: "Built-in workflow. After you complete the intake walkaround, the system prompts the customer to post the before — or you take it yourself and tag them. Easier than asking them to remember." },
      { question: "What if my service area is small?", answer: "Local-zip-code analytics will show you exactly which neighborhoods perform best, and the local reach is actually higher per post than for businesses with broader geography." },
      { question: "Can I include detail products in the perk mix?", answer: "Yes. Many detailers offer branded microfiber bundles, ceramic spray, or interior cleaner as perks. Drives merchandise revenue too." },
      { question: "What about fleet customers?", answer: "Fleet-mode lets a single account manager redeem perks for their drivers' posts. Builds your local-commercial reputation and helps close more fleet contracts." },
      { question: "Does it work if I don't do social media myself?", answer: "Yes. The system runs without you needing to post anything personally. Your customers do the posting." },
      { question: "What's the average bookings lift?", answer: "Most mobile detailers see 25-50% more inbound bookings in the first 90 days, almost entirely from organic posts." },
    ],
    quickStart: [
      "Sign up and connect Instagram and Google",
      "Set up your default 'Before-and-after carousel' campaign",
      "Order rear-window QR sticker pack (we send them)",
      "Mention the perk at intake and after final walkaround on your next 5 jobs",
      "Track post reach and inbound bookings in your dashboard weekly",
    ],
  },
  {
    slug: "house-cleaners",
    niche: "house cleaning services",
    nicheSingular: "house cleaning service",
    category: "service",
    hook: "Turn happy clients into referrers.",
    h1: "For house cleaning services: turn happy clients into referrers",
    heroPain: "Your team leaves a house spotless every Tuesday. The client texts a heart emoji and books another clean. They never tell their friends, never post on Nextdoor, never leave a review. Social Perks fixes that.",
    heroSubhead: "Clients earn discounts on next cleans, free deep-clean upgrades, and free add-ons every time they post a clean-house Reel, recommend you on Nextdoor, or refer a neighbor. You clean. They share. Your route fills with referrals.",
    builtForIntro: "House cleaning is a referral-first business with one of the lowest natural posting rates of any service. Clients love you but never think to share. Social Perks builds a structured share-and-refer engine into your operations.",
    builtFor: [
      { title: "Walkthrough-Reel capture", description: "After-clean walkthroughs — sparkling counters, made beds, fresh-vacuumed carpets — are highly shareable but rarely captured. Built-in prompts and example Reels show clients exactly what to post." },
      { title: "Nextdoor and Facebook neighborhood activation", description: "Special perk tracks for posts in neighborhood Facebook groups and Nextdoor — the highest-conversion channels for cleaning services. Reach the exact buyer." },
      { title: "Referral-with-attribution perks", description: "Built-in referral codes — when a friend signs up via a client's code, both get a perk. Clean attribution, no manual tracking." },
      { title: "Recurring-client perk loops", description: "Bi-weekly and weekly clients build perk credits over months. Long-term retention reward that incentivizes both staying with you and posting." },
      { title: "Team-pride campaigns", description: "Optional 'who cleaned today' attribution lets clients tag the specific cleaner who served them. Boosts team pride and gives you per-cleaner satisfaction data." },
    ],
    campaigns: [
      { name: "Clean-house walkthrough Reel", description: "Client records a walkthrough Reel after a clean, tagging your business.", perk: "$20 off next clean" },
      { name: "Nextdoor recommendation post", description: "Client posts a recommendation in their Nextdoor neighborhood group.", perk: "Free oven or fridge deep-clean add-on" },
      { name: "Refer-a-friend signup", description: "Client refers a friend who books at least one clean.", perk: "$50 toward future cleans for the referrer, $25 off first clean for the friend" },
      { name: "Detailed Google review", description: "Long, specific Google review with photos.", perk: "Free deep-clean upgrade on next service" },
      { name: "Before-and-after move-out post", description: "Move-out client posts a before-and-after carousel.", perk: "Discount on their first clean at their new home" },
    ],
    unfairAdvantageIntro: "Why happy cleaning clients are the highest-trust referrers in any service vertical:",
    unfairAdvantage: [
      { title: "House-into-someone's-house is intimate", description: "Trusting someone to clean your home is one of the most personal services. A recommendation from a real client overcomes the trust barrier instantly for new customers." },
      { title: "Neighborhood-network reach", description: "Cleaning customers cluster geographically. A Nextdoor post in one neighborhood reaches 200-500 potential customers in your exact service area. Higher ROI than any paid channel." },
      { title: "High lifetime value, low churn", description: "Cleaning clients stay 2-5 years on average. One enrolled client can post or refer 20+ times. Compounded across 50 clients, that's a self-sustaining lead engine." },
    ],
    faqs: [
      { question: "My clients are private — they don't want to post their homes online. Will this work?", answer: "Many cleaning posts don't show the home at all. Detail shots of clean counters, fresh-vacuumed rugs, organized closets — no identifiable rooms. Plus Nextdoor and Facebook recommendations don't require photos at all." },
      { question: "Will this conflict with my team's privacy with clients?", answer: "No — the perk is for the client posting about you, not your team posting about clients. Your team's privacy and your client's privacy are fully separated." },
      { question: "I run weekly and bi-weekly clients. Can I throttle perks per visit?", answer: "Yes. Set perks to unlock max once per month, even if a client posts more often. Keeps redemption cost predictable." },
      { question: "What about commercial cleaning clients?", answer: "Commercial campaigns work too — office cleaning managers post Friday-evening walkthroughs of clean spaces. Useful for B2B social proof." },
      { question: "How does the referral attribution work?", answer: "Each client gets a unique referral code in their wallet. When a new customer enters that code at booking, the system credits the referrer automatically." },
      { question: "Will the AI catch fake or staged posts?", answer: "Yes — our review pipeline detects stock photos, fake walkthroughs, and AI-generated content. Only authentic posts unlock perks." },
      { question: "How quickly do clients enroll?", answer: "Around 50-60% of clients enroll in the first month if you mention it once during a clean and follow up with the signup link via text." },
    ],
    quickStart: [
      "Sign up and connect Google Business and Instagram",
      "Set up the 'Clean-house walkthrough Reel' starter campaign",
      "Add the perk signup link to your post-clean thank-you SMS",
      "Mention it once at the end of your next 10 cleans",
      "Watch reviews, referrals, and Nextdoor mentions climb weekly",
    ],
  },
  {
    slug: "dog-groomers",
    niche: "dog groomers",
    nicheSingular: "dog groomer",
    category: "service",
    hook: "Pet parents love sharing photos.",
    h1: "For dog groomers: pet parents love sharing photos",
    heroPain: "You just turned a matted golden doodle into a magazine cover and the owner cried when she picked him up. She posted one photo to her close friends story. Six people saw it. Social Perks fixes that.",
    heroSubhead: "Pet parents earn grooming discounts, free de-shedding add-ons, and treat-bag perks every time they post a fresh-cut shot, a Reel, or a review. You groom. They post. Your booking calendar fills six weeks out.",
    builtForIntro: "Dog grooming has the most enthusiastic, photo-happy customer base of any service vertical. Pet parents post their dogs anyway. Social Perks makes sure those posts tag you, drive bookings, and earn rewards.",
    builtFor: [
      { title: "Fresh-cut window prompts", description: "Auto-prompts go out 2-6 hours post-pickup — the prime fresh-cut photo window before life happens to the haircut. Pre-built Reel templates for the 'reveal' moment." },
      { title: "Breed and style campaigns", description: "Doodle hand-scissoring, schnauzer pattern, poodle continental — per-style campaign perks recognize the artistry. Premium grooms earn premium perks." },
      { title: "Spa-day perk routing", description: "Native perk types: free nail trim, free de-shedding, free teeth brush, premium shampoo upgrade, treat bag at pickup. Match how groomers actually reward." },
      { title: "Anxiety-aware client tracking", description: "For anxious-dog clients, low-pressure perk types (review-only, no photo required) keep the program accessible to clients who'd never post their nervous dog." },
      { title: "Solo and small-shop pricing", description: "$49/month flat for one groomer. No per-pet fees, no commercial-shop premium. Built for solo mobile groomers and small studios." },
    ],
    campaigns: [
      { name: "Fresh-cut feed photo", description: "Pet parent posts a fresh-cut photo within 24 hours.", perk: "$10 off next groom" },
      { name: "Reveal Reel", description: "Reel showing the before-and-after of the groom.", perk: "Free de-shedding on next visit" },
      { name: "Breed-specific style carousel", description: "Multi-image carousel of intricate breed-specific styling.", perk: "Free nail trim for life" },
      { name: "Anxious-dog wellness review", description: "Detailed Google review focused on calm handling and pet comfort.", perk: "Free spa-shampoo upgrade" },
      { name: "Holiday or seasonal-style post", description: "Holiday bandana, themed bow, or seasonal style post.", perk: "Free seasonal accessory next visit" },
    ],
    unfairAdvantageIntro: "Why dog-groomer customers post at higher rates than any other service customer base:",
    unfairAdvantage: [
      { title: "Pet parents post everything", description: "Dog owners post their dogs daily anyway. You're not asking them to do something new — you're asking them to add a tag to content they were going to post no matter what." },
      { title: "Algorithm loves dogs", description: "Dog posts consistently outperform other content across every platform. A fresh-cut Reel routinely reaches 5,000+ people for free." },
      { title: "Recurring service = recurring posts", description: "Most groom clients return every 4-6 weeks. That's 8-12 posts per client per year. With 80 active clients, you have a 640-960-post annual content engine." },
    ],
    faqs: [
      { question: "Will this work for mobile groomers without a salon?", answer: "Perfectly. Mobile groomers benefit even more because clients want to show off how cute their dog looks AND brag about the convenience of mobile service. Strong content angles in both directions." },
      { question: "Some of my clients have nervous dogs. Can they participate without posting photos?", answer: "Yes. Review-only campaigns (no photo required) let nervous-dog clients still earn perks via Google reviews. About 30% of groomers' programs use review-only tracks." },
      { question: "Can I track which breeds drive the most new bookings?", answer: "Yes. Per-breed analytics show which breed cuts pull in new bookings — useful for marketing specialty styles or targeting underserved breed types in your market." },
      { question: "What if a client posts a photo that's blurry or unflattering?", answer: "AI review pipeline flags low-quality photos before perks unlock. Optional re-shoot prompt helps clients get a better post." },
      { question: "Do I have to handle FTC disclosures for pet-influencer accounts?", answer: "Yes, and we automate it. Pet-influencer accounts and regular pet-parent accounts both auto-tag posts correctly per FTC." },
      { question: "Can groomer-of-the-day attribution work in a shop with multiple stylists?", answer: "Yes. Per-stylist attribution lets clients tag the specific groomer. Builds individual stylist books, helpful for retention and promotions." },
      { question: "How long until I see results?", answer: "First posts come within a week of launch. Measurable booking impact usually within 30 days. Average new-booking lift is 25-35% in the first 90 days." },
    ],
    quickStart: [
      "Sign up and connect Instagram and Google",
      "Set up the 'Fresh-cut feed photo' starter campaign",
      "Add the perk signup link to your appointment-confirmation text",
      "Hand a treat bag with a QR-code tag attached at pickup for the next 10 clients",
      "Track post volume and new bookings in your dashboard weekly",
    ],
  },
  {
    slug: "wedding-photographers",
    niche: "wedding photographers",
    nicheSingular: "wedding photographer",
    category: "service",
    hook: "Portfolio + perks = bookings.",
    h1: "For wedding photographers: portfolio + perks = bookings",
    heroPain: "You delivered 800 stunning images to a couple. They picked 12 for Instagram, tagged you in 3, and the rest sat in a Google Drive. Their friends getting engaged next year never saw your work. Social Perks fixes that.",
    heroSubhead: "Couples earn print credits, anniversary-session discounts, and engagement-gift perks every time they post their gallery, share a Reel, or recommend you. You shoot. They share. Their newly-engaged friends find you.",
    builtForIntro: "Wedding photography is referral- and portfolio-driven. Every wedding produces hundreds of postable images and every couple has 50+ engaged friends. Social Perks turns post-wedding gallery delivery into a 12-month organic marketing engine.",
    builtFor: [
      { title: "Gallery-delivery campaign launch", description: "Campaign auto-spins-up when you deliver the gallery. The couple gets the perk system as part of their delivery package — incentive to post is hottest right when they're sharing photos with everyone." },
      { title: "Engagement-shoot-to-wedding loop", description: "Engagement-session campaign rolls into wedding-day campaign rolls into one-year-anniversary campaign. Three full posting cycles per couple, each with its own perk." },
      { title: "Tagged-couple-network analytics", description: "Track which couples' posts reach the most newly-engaged followers. Identify your best ambassador couples and reward them with elevated perks (anniversary sessions, print credits)." },
      { title: "Album-and-print perk integration", description: "Native perks include print credits, album upgrades, fine-art prints — products you're already selling, now incentivizing posting too." },
      { title: "Venue and vendor co-perks", description: "Partner with venues and other vendors (florists, planners) for stacked perks. Couples post crediting all of you, vendors split the perk cost, everyone wins." },
    ],
    campaigns: [
      { name: "Gallery sneak-peek post", description: "Couple posts a Reel or carousel from the delivered gallery tagging you.", perk: "$100 print credit" },
      { name: "Wedding-day teaser story share", description: "Couple posts a same-day or next-day teaser story from your sneak-peek images.", perk: "Free 8x10 print of their choice" },
      { name: "One-year-anniversary post", description: "Couple posts on their one-year anniversary sharing a favorite image.", perk: "50% off anniversary mini-session" },
      { name: "Vendor co-tag carousel", description: "Couple posts crediting you AND venue/florist/planner with a multi-image carousel.", perk: "Free album upgrade (cost shared with vendor partners)" },
      { name: "Detailed review on Google + The Knot", description: "Long detailed review on both platforms within 60 days post-wedding.", perk: "$150 toward fine-art prints" },
    ],
    unfairAdvantageIntro: "Why wedding-photography customers are unmatched ambassadors compared to any other service vertical:",
    unfairAdvantage: [
      { title: "Engaged-friend network density", description: "Every couple has at least 5-10 newly-engaged or about-to-be-engaged friends in their close network. A single post reaches the exact audience most likely to book within the next 18 months." },
      { title: "Highest-emotion content", description: "Wedding content gets the highest engagement on every platform. The algorithm boosts it, friends comment on it, family shares it. Free reach far above other verticals." },
      { title: "Long-cycle posting", description: "Couples post wedding photos for years — anniversaries, throwbacks, milestone moments. One wedding produces a decade of organic content if structured right." },
    ],
    faqs: [
      { question: "I only do 25-30 weddings a year. Is this worth it for a low-volume photographer?", answer: "Especially yes. At 25 weddings × 50 engaged friends per couple = 1,250 high-intent local prospects per year reached. That's better than most paid-ad budgets at zero cost." },
      { question: "What about couples who want full image privacy?", answer: "Opt-in. About 70% of couples enroll, the rest stay private. No pressure, no loss for you — the 70% drives the 30% increase in bookings." },
      { question: "Will this work for elopement or destination photographers?", answer: "Yes, and arguably better. Elopement and destination posts get higher engagement and reach because they're more visually distinct. Smaller volume, larger per-post impact." },
      { question: "Can I include print-shop revenue in this?", answer: "Yes. Print credits and album upgrades drive print revenue while incentivizing posting. The two are designed to reinforce each other." },
      { question: "What about vendor partnerships?", answer: "Native co-vendor perks let venues, florists, and planners share perk costs and reach. Strengthens vendor referrals and gives couples more reasons to post." },
      { question: "How does the anniversary campaign work without me having to remember?", answer: "Automated. Anniversary perks fire one year after the wedding date you set during onboarding the couple. Drives anniversary mini-session bookings every year." },
      { question: "Will it integrate with my gallery-delivery platform?", answer: "Yes — Pixieset, Pic-Time, ShootProof, and SmugMug integrate directly. Perk signup link appears alongside the gallery delivery." },
    ],
    quickStart: [
      "Sign up and connect Instagram and your gallery-delivery platform",
      "Set up the 'Gallery sneak-peek post' starter campaign",
      "Add the perk signup link to your gallery-delivery email template",
      "Email your last 10 couples to retroactively invite them in",
      "Track post reach, anniversary bookings, and vendor referrals quarterly",
    ],
  },
  {
    slug: "real-estate-agents",
    niche: "real estate agents",
    nicheSingular: "real estate agent",
    category: "service",
    hook: "Every closing is a story.",
    h1: "For real estate agents: every closing is a story",
    heroPain: "You closed five deals this quarter and not one of those clients posted about you. Their friends, their families, and their coworkers — all your next ideal buyers — never heard the story of how you found them their dream home. Social Perks fixes that.",
    heroSubhead: "Clients earn closing gifts, anniversary-of-purchase perks, and home-service credits every time they post a key-in-hand photo, a closing-day Reel, or a recommendation. You close. They post. Your pipeline fills with referrals.",
    builtForIntro: "Real estate is a referral business and every closing is a story your client wants to tell. Social Perks structures the post-closing posting moment, the one-year-anniversary, and the home-improvement journey into a 5-year referral engine per client.",
    builtFor: [
      { title: "Closing-day moment capture", description: "Auto-launch a campaign on closing day. Client posts the key-in-hand photo, a closing-day Reel, or a 'we got the house!' announcement — earns a closing-gift perk." },
      { title: "Move-in and anniversary loops", description: "Move-in week campaign, 6-month homeowner-tip campaign, one-year purchase-anniversary campaign. Three full posting windows per client, each producing referrals." },
      { title: "Home-service vendor network", description: "Partner with painters, handymen, lawn services, cleaners. Clients earn perks at vendors you trust, vendors gain qualified leads, you stay top-of-mind through every home project." },
      { title: "Listing-promotion campaigns", description: "Past clients can earn perks for sharing your new listings — your own ambassador network reaching their neighborhood circles." },
      { title: "Solo-agent and small-team friendly", description: "$49/month flat. No per-transaction fees, no enterprise pricing for solo agents." },
    ],
    campaigns: [
      { name: "Key-in-hand closing photo", description: "Client posts a closing-day photo tagging the agent.", perk: "$100 closing gift toward home-service vendor" },
      { name: "Move-in week Reel", description: "Client posts a Reel of move-in or first night in the new home.", perk: "Free professional home photoshoot (anniversary gift)" },
      { name: "Listing share by past client", description: "Past client shares your new listing with their network.", perk: "$50 home-services credit per shared listing that sells" },
      { name: "One-year-anniversary post", description: "Client posts a 'one year ago today' moment on their purchase anniversary.", perk: "Free professional home valuation report" },
      { name: "Detailed Google + Zillow review", description: "Long detailed reviews on both platforms within 30 days of closing.", perk: "$200 home-services credit" },
    ],
    unfairAdvantageIntro: "Why real-estate clients are uniquely valuable referrers compared to almost any other service:",
    unfairAdvantage: [
      { title: "Life-event-level emotional posts", description: "Buying a home is one of the biggest moments in a person's life. Closing posts get massive engagement from friends, family, and coworkers — exactly the people about to be in the market." },
      { title: "Network-aligned audience", description: "Most homebuyers are surrounded by other people in similar life stages. A new homeowner's closing post reaches dozens of friends within 1-3 years of their own purchase." },
      { title: "Multi-year referral arc", description: "Clients post at closing, at move-in, at 6 months, at one year, at 5 years (\"we're outgrowing this house\"). Each post is a potential referral. Few service businesses get 5 years of organic content per customer." },
    ],
    faqs: [
      { question: "Does this work for new agents or only high-producers?", answer: "Especially well for newer agents. The system levels the playing field by structuring referrals that established agents get organically. New agents using Social Perks see referral lift 40-60% in year one." },
      { question: "What about luxury clients who don't post publicly?", answer: "Luxury clients participate via private channels — newsletter shares, review writing, vendor referrals — instead of public posts. About 25% of high-end clients still enroll for the home-service vendor perks." },
      { question: "Can I partner with mortgage lenders or title companies?", answer: "Yes. Partner-perks let lenders, title companies, and insurance agents co-fund client gifts. Strengthens partnership and shares marketing cost." },
      { question: "How does the anniversary campaign work without me having to track?", answer: "Automated by closing date entered at signup. Anniversary perks fire automatically, your past client gets a notification, and they post — without you doing anything." },
      { question: "Does this conflict with my brokerage's marketing rules?", answer: "We support brokerage-branded campaigns alongside agent-branded ones. Most brokerages encourage tools like this because agent-generated referrals strengthen the whole office." },
      { question: "What about TRESPA or RESPA compliance with vendor partnerships?", answer: "Built in. Vendor partnerships and co-marketing perks comply with RESPA section 8 — no improper kickback structure, all gifts are transparent and tracked." },
      { question: "Will it integrate with my CRM?", answer: "Follow Up Boss, KvCORE, Top Producer, Sierra, Wise Agent all integrate directly. Closings and anniversaries auto-trigger from your CRM data." },
    ],
    quickStart: [
      "Sign up and connect Instagram and your CRM",
      "Set up the 'Key-in-hand closing photo' starter campaign",
      "Add the perk signup link to your closing-day gift card",
      "Retroactively invite your past clients from the last 12 months via email",
      "Watch closing posts, anniversary engagement, and referrals build quarter over quarter",
    ],
  },
];

export const COMMUNITY_MAP = new Map(COMMUNITIES.map((c) => [c.slug, c]));
export const COMMUNITY_SLUGS = COMMUNITIES.map((c) => c.slug);

export const CATEGORY_LABELS: Record<CommunityCategory, string> = {
  creator: "Creator and influencer audiences",
  food: "Food and beverage operators",
  service: "Service businesses",
};

export const CATEGORY_DESCRIPTIONS: Record<CommunityCategory, string> = {
  creator:
    "Independent creators, instructors, and artists whose customers are already documenting the experience — structured perks turn that into reach.",
  food:
    "Restaurants, trucks, and beverage operators where every visit is a photo opportunity and every regular is a local micro-influencer.",
  service:
    "Home and personal service businesses where every job produces a story worth sharing — and every happy client is a future referral.",
};
