/**
 * AI Marketing Campaign Agent — Business Type Profiles
 *
 * Pre-defined profiles for common business types that inform
 * the agent's recommendations and analysis.
 */

import { detectTraits } from "../ai-engine";
import type { BusinessTypeProfile } from "./types";

export const BUSINESS_TYPE_PROFILES: Record<string, BusinessTypeProfile> = {
  "yoga studio": {
    traits: ["visual", "wellness", "transform", "community"],
    typicalCustomer: "Health-conscious individuals aged 25-55 seeking mind-body wellness",
    visitFrequency: "weekly",
    avgTransactionValue: 25,
    bestChannels: ["ig", "tt", "go", "fb", "yt"],
    contentTypes: ["before/after transformations", "class previews", "instructor spotlights", "student progress", "mindfulness tips"],
    marketingStrengths: ["visual transformation content", "community building", "wellness lifestyle aspiration"],
    keyMetrics: ["class attendance", "membership retention", "new student signups"],
    membershipBased: true,
    seasonalPeaks: ["January (resolutions)", "March-April (spring reset)", "September (back to routine)"],
  },
  "coffee shop": {
    traits: ["food", "visual", "local", "community"],
    typicalCustomer: "Daily coffee drinkers, remote workers, students aged 18-45",
    visitFrequency: "daily",
    avgTransactionValue: 7,
    bestChannels: ["ig", "tt", "go", "fb", "gm"],
    contentTypes: ["latte art", "barista skills", "cozy atmosphere", "seasonal drinks", "food pairings"],
    marketingStrengths: ["high visit frequency", "photogenic products", "community gathering spot"],
    keyMetrics: ["daily transactions", "average ticket size", "repeat customer rate"],
    membershipBased: false,
    seasonalPeaks: ["Fall (PSL season)", "Winter (cozy drinks)", "Summer (iced drinks)"],
  },
  restaurant: {
    traits: ["food", "visual", "hospitality", "local"],
    typicalCustomer: "Diners looking for experiences, couples, families, food enthusiasts aged 25-60",
    visitFrequency: "biweekly",
    avgTransactionValue: 45,
    bestChannels: ["ig", "tt", "go", "yp", "fb", "gm"],
    contentTypes: ["food photography", "chef features", "behind-the-scenes", "taste reactions", "seasonal menus"],
    marketingStrengths: ["highly shareable food content", "review-driven discovery", "special occasion marketing"],
    keyMetrics: ["covers per night", "average check size", "review rating", "repeat visits"],
    membershipBased: false,
    seasonalPeaks: ["Valentine's Day", "Mother's Day", "Holiday season", "Summer patios"],
  },
  gym: {
    traits: ["wellness", "transform", "visual", "community"],
    typicalCustomer: "Fitness enthusiasts, transformation seekers aged 18-50",
    visitFrequency: "weekly",
    avgTransactionValue: 60,
    bestChannels: ["ig", "tt", "go", "yt", "fb"],
    contentTypes: ["transformation stories", "workout clips", "trainer spotlights", "community events", "progress updates"],
    marketingStrengths: ["dramatic visual transformations", "high engagement community", "goal-oriented content"],
    keyMetrics: ["membership count", "retention rate", "class attendance", "new signups"],
    membershipBased: true,
    seasonalPeaks: ["January (resolutions)", "March-May (summer prep)", "September (back to routine)"],
  },
  salon: {
    traits: ["visual", "transform", "luxury", "local"],
    typicalCustomer: "Style-conscious individuals, special occasion clients aged 20-60",
    visitFrequency: "monthly",
    avgTransactionValue: 75,
    bestChannels: ["ig", "tt", "go", "fb", "pi"],
    contentTypes: ["before/after reveals", "color transformations", "styling tutorials", "trend showcases", "client reveals"],
    marketingStrengths: ["dramatic transformations", "highly visual results", "aspirational content"],
    keyMetrics: ["booking rate", "average service value", "rebooking rate", "review rating"],
    membershipBased: false,
    seasonalPeaks: ["Prom season", "Wedding season", "Holiday parties", "Back to school"],
  },
  "tattoo parlor": {
    traits: ["visual", "transform", "art", "local"],
    typicalCustomer: "Art lovers, self-expression seekers aged 18-45",
    visitFrequency: "quarterly",
    avgTransactionValue: 200,
    bestChannels: ["ig", "tt", "go", "pi", "rd"],
    contentTypes: ["process videos", "finished pieces", "artist portfolios", "flash events", "healing progress"],
    marketingStrengths: ["unique visual content", "artist-driven following", "portfolio-based marketing"],
    keyMetrics: ["booking rate", "average piece value", "portfolio reach", "artist wait time"],
    membershipBased: false,
    seasonalPeaks: ["Friday the 13th flash sales", "Convention season", "Holiday gift certificates"],
  },
  "dental practice": {
    traits: ["healthcare", "service", "transform", "local"],
    typicalCustomer: "Families, professionals seeking routine and cosmetic care aged 25-65",
    visitFrequency: "quarterly",
    avgTransactionValue: 150,
    bestChannels: ["go", "fb", "gm", "ig", "nd"],
    contentTypes: ["smile transformations", "patient testimonials", "dental tips", "office tours", "team introductions"],
    marketingStrengths: ["trust-building through reviews", "before/after results", "community presence"],
    keyMetrics: ["new patient signups", "patient retention", "review rating", "case acceptance rate"],
    membershipBased: false,
    seasonalPeaks: ["Back to school", "New year (insurance reset)", "Spring cleaning"],
  },
  veterinarian: {
    traits: ["pets", "healthcare", "service", "local"],
    typicalCustomer: "Pet owners who treat their animals like family, aged 25-60",
    visitFrequency: "quarterly",
    avgTransactionValue: 120,
    bestChannels: ["ig", "fb", "go", "gm", "tt"],
    contentTypes: ["cute pet photos", "recovery stories", "pet health tips", "team with animals", "adoption events"],
    marketingStrengths: ["emotionally powerful pet content", "trust through care stories", "community events"],
    keyMetrics: ["new clients", "client retention", "review rating", "average visit value"],
    membershipBased: false,
    seasonalPeaks: ["Puppy season (spring)", "Holiday boarding", "Adopt a pet month"],
  },
  florist: {
    traits: ["visual", "retail", "seasonal", "local"],
    typicalCustomer: "Gift buyers, event planners, home decor enthusiasts aged 25-55",
    visitFrequency: "monthly",
    avgTransactionValue: 55,
    bestChannels: ["ig", "pi", "go", "fb", "tt"],
    contentTypes: ["arrangement showcases", "behind-the-scenes", "seasonal collections", "wedding features", "DIY tips"],
    marketingStrengths: ["extremely photogenic product", "occasion-driven purchases", "gift-giving shares"],
    keyMetrics: ["order volume", "average order value", "event bookings", "repeat customers"],
    membershipBased: false,
    seasonalPeaks: ["Valentine's Day", "Mother's Day", "Wedding season", "Holiday season"],
  },
  "auto mechanic": {
    traits: ["automotive", "service", "local"],
    typicalCustomer: "Vehicle owners seeking trustworthy service, all ages",
    visitFrequency: "quarterly",
    avgTransactionValue: 180,
    bestChannels: ["go", "gm", "fb", "nd", "yp"],
    contentTypes: ["repair explanations", "honest assessments", "before/after repairs", "maintenance tips", "team expertise"],
    marketingStrengths: ["trust-building reviews", "educational content", "neighborhood presence"],
    keyMetrics: ["new customers", "repeat rate", "average repair value", "review rating"],
    membershipBased: false,
    seasonalPeaks: ["Pre-winter prep", "Spring road trip season", "Back to school"],
  },
  "law firm": {
    traits: ["b2b", "service", "local"],
    typicalCustomer: "Individuals and businesses needing legal representation, aged 30-65",
    visitFrequency: "yearly",
    avgTransactionValue: 500,
    bestChannels: ["go", "li", "fb", "gm", "nd"],
    contentTypes: ["legal tips", "case study insights", "team credentials", "community involvement", "FAQ answers"],
    marketingStrengths: ["authority building", "trust through expertise", "professional network effects"],
    keyMetrics: ["new clients", "case volume", "referral rate", "review rating"],
    membershipBased: false,
    seasonalPeaks: ["Tax season", "New year (resolutions)", "Estate planning season"],
  },
  bakery: {
    traits: ["food", "visual", "retail", "local"],
    typicalCustomer: "Treat seekers, special occasion buyers, foodies aged 20-55",
    visitFrequency: "weekly",
    avgTransactionValue: 15,
    bestChannels: ["ig", "tt", "go", "fb", "pi"],
    contentTypes: ["baking process", "decorating reveals", "seasonal specials", "custom order showcases", "taste tests"],
    marketingStrengths: ["visually stunning products", "shareable content", "gift-driven purchases"],
    keyMetrics: ["daily sales", "custom order volume", "social shares", "repeat customers"],
    membershipBased: false,
    seasonalPeaks: ["Holiday season", "Valentine's Day", "Wedding season", "Back to school"],
  },
  "escape room": {
    traits: ["entertainment", "visual", "local"],
    typicalCustomer: "Friend groups, team builders, experience seekers aged 18-45",
    visitFrequency: "quarterly",
    avgTransactionValue: 35,
    bestChannels: ["ig", "tt", "go", "fb", "gm"],
    contentTypes: ["group reaction videos", "escape celebrations", "puzzle teases", "team building events", "behind-the-scenes"],
    marketingStrengths: ["group experience sharing", "FOMO-driven content", "corporate team building"],
    keyMetrics: ["bookings per week", "group size", "review rating", "rebooking rate"],
    membershipBased: false,
    seasonalPeaks: ["Team building season (Q1/Q3)", "Holiday parties", "Summer activities"],
  },
  "pizza chain": {
    traits: ["food", "visual", "local"],
    typicalCustomer: "Everyone — families, students, office workers, all ages",
    visitFrequency: "weekly",
    avgTransactionValue: 22,
    bestChannels: ["ig", "tt", "go", "fb", "gm", "yp"],
    contentTypes: ["pizza making", "cheese pulls", "taste tests", "delivery moments", "specials announcements"],
    marketingStrengths: ["universally loved product", "highly visual (cheese pulls!)", "frequent purchases"],
    keyMetrics: ["daily orders", "average order value", "delivery vs dine-in", "repeat rate"],
    membershipBased: false,
    seasonalPeaks: ["Super Bowl", "Friday nights year-round", "Back to school"],
  },
  spa: {
    traits: ["wellness", "luxury", "visual", "transform"],
    typicalCustomer: "Self-care seekers, gift recipients, stressed professionals aged 25-60",
    visitFrequency: "monthly",
    avgTransactionValue: 120,
    bestChannels: ["ig", "go", "fb", "pi", "tt"],
    contentTypes: ["relaxation environments", "treatment showcases", "before/after skin", "self-care tips", "gift packages"],
    marketingStrengths: ["aspirational lifestyle content", "gift-driven marketing", "visual relaxation"],
    keyMetrics: ["booking rate", "package sales", "gift card revenue", "retention rate"],
    membershipBased: true,
    seasonalPeaks: ["Valentine's Day", "Mother's Day", "Holiday gifting", "New year reset"],
  },
  boutique: {
    traits: ["retail", "visual", "luxury", "local"],
    typicalCustomer: "Fashion-forward shoppers seeking unique pieces, aged 20-50",
    visitFrequency: "biweekly",
    avgTransactionValue: 65,
    bestChannels: ["ig", "tt", "pi", "fb", "go"],
    contentTypes: ["styling tips", "new arrivals", "try-on hauls", "outfit of the day", "behind-the-scenes sourcing"],
    marketingStrengths: ["curated aesthetic", "influencer collaboration potential", "trend-driven content"],
    keyMetrics: ["foot traffic", "average sale", "online inquiries", "social followers"],
    membershipBased: false,
    seasonalPeaks: ["Fashion weeks", "Holiday shopping", "Spring collections", "Back to school"],
  },
  brewery: {
    traits: ["food", "visual", "entertainment", "local"],
    typicalCustomer: "Craft beer enthusiasts, social groups, foodies aged 21-50",
    visitFrequency: "biweekly",
    avgTransactionValue: 35,
    bestChannels: ["ig", "tt", "go", "fb", "yp"],
    contentTypes: ["brew process", "tasting flights", "new release announcements", "taproom vibes", "pairing suggestions"],
    marketingStrengths: ["passionate niche audience", "event marketing", "community culture"],
    keyMetrics: ["taproom visits", "average tab", "event attendance", "distribution growth"],
    membershipBased: false,
    seasonalPeaks: ["Oktoberfest", "Summer patios", "St. Patrick's Day", "Holiday releases"],
  },
  "real estate": {
    traits: ["b2b", "service", "visual", "local"],
    typicalCustomer: "Home buyers, sellers, investors aged 28-65",
    visitFrequency: "yearly",
    avgTransactionValue: 1000,
    bestChannels: ["ig", "fb", "go", "li", "yt"],
    contentTypes: ["listing tours", "market updates", "homebuyer tips", "just-sold celebrations", "neighborhood guides"],
    marketingStrengths: ["high-value transaction marketing", "visual property content", "referral-driven"],
    keyMetrics: ["listings", "closings", "referral rate", "average sale price"],
    membershipBased: false,
    seasonalPeaks: ["Spring market", "Back to school moves", "Year-end tax moves"],
  },
  roofer: {
    traits: ["visual", "service", "transform"],
    typicalCustomer: "Homeowners needing roof repair or replacement, aged 30-70",
    visitFrequency: "once",
    avgTransactionValue: 12000,
    bestChannels: ["go", "gm", "nd", "fb", "ig"],
    contentTypes: ["before_after_photos", "drone_footage", "video_testimonial", "detailed_review", "neighborhood_recommendation"],
    marketingStrengths: ["dramatic visual transformations", "high-value word-of-mouth", "neighborhood clustering effect"],
    keyMetrics: ["lead volume", "close rate", "average job value", "review rating"],
    membershipBased: false,
    seasonalPeaks: ["Spring", "Summer", "Fall"],
  },
  plumber: {
    traits: ["service"],
    typicalCustomer: "Homeowners and renters needing plumbing repair, all ages",
    visitFrequency: "rare",
    avgTransactionValue: 800,
    bestChannels: ["go", "gm", "nd", "fb"],
    contentTypes: ["before_after_photos", "video_testimonial", "review"],
    marketingStrengths: ["trust-critical service", "emergency search dominance", "neighborhood referral networks"],
    keyMetrics: ["call volume", "average job value", "review rating", "response time"],
    membershipBased: false,
    seasonalPeaks: ["Winter", "Spring"],
  },
  hvac: {
    traits: ["service"],
    typicalCustomer: "Homeowners needing heating/cooling service or installation, aged 30-70",
    visitFrequency: "seasonal",
    avgTransactionValue: 3000,
    bestChannels: ["go", "gm", "nd", "fb"],
    contentTypes: ["review", "video_testimonial", "before_after_photos"],
    marketingStrengths: ["seasonal demand spikes", "maintenance contract potential", "emergency search presence"],
    keyMetrics: ["service calls", "install jobs", "maintenance contracts", "review rating"],
    membershipBased: false,
    seasonalPeaks: ["Summer", "Winter"],
  },
  landscaper: {
    traits: ["visual", "service", "transform"],
    typicalCustomer: "Homeowners seeking lawn care, landscaping design, or hardscaping, aged 30-65",
    visitFrequency: "recurring",
    avgTransactionValue: 2500,
    bestChannels: ["ig", "go", "gm", "nd", "fb", "tt"],
    contentTypes: ["before_after_photos", "timelapse", "drone_footage", "seasonal_showcase"],
    marketingStrengths: ["highly visual transformations", "seasonal content calendar", "neighborhood visibility"],
    keyMetrics: ["recurring clients", "project value", "review rating", "referral rate"],
    membershipBased: false,
    seasonalPeaks: ["Spring", "Summer"],
  },
  electrician: {
    traits: ["service"],
    typicalCustomer: "Homeowners and businesses needing electrical work, all ages",
    visitFrequency: "rare",
    avgTransactionValue: 1500,
    bestChannels: ["go", "gm", "nd", "fb"],
    contentTypes: ["review", "before_after_photos"],
    marketingStrengths: ["trust-critical service", "project-based referrals", "safety expertise content"],
    keyMetrics: ["job volume", "average project value", "review rating", "referral rate"],
    membershipBased: false,
    seasonalPeaks: ["Spring", "Fall"],
  },
  "general contractor": {
    traits: ["visual", "service", "transform"],
    typicalCustomer: "Homeowners planning major renovations or new construction, aged 30-65",
    visitFrequency: "once",
    avgTransactionValue: 50000,
    bestChannels: ["ig", "go", "gm", "fb", "yt", "pi"],
    contentTypes: ["before_after_photos", "project_timelapse", "video_walkthrough", "detailed_review", "drone_footage"],
    marketingStrengths: ["portfolio-driven sales", "dramatic transformation content", "high-value referrals"],
    keyMetrics: ["project pipeline", "average project value", "review rating", "portfolio reach"],
    membershipBased: false,
    seasonalPeaks: ["Spring", "Summer", "Fall"],
  },
  painter: {
    traits: ["visual", "service", "transform"],
    typicalCustomer: "Homeowners seeking interior or exterior painting, aged 25-65",
    visitFrequency: "rare",
    avgTransactionValue: 4000,
    bestChannels: ["ig", "go", "gm", "nd", "fb", "pi"],
    contentTypes: ["before_after_photos", "color_reveal", "timelapse", "review"],
    marketingStrengths: ["highly visual color transformations", "aspirational home content", "neighborhood word-of-mouth"],
    keyMetrics: ["jobs per month", "average project value", "review rating", "referral rate"],
    membershipBased: false,
    seasonalPeaks: ["Spring", "Summer"],
  },
};

export function getBusinessTypeProfile(type: string): BusinessTypeProfile {
  const lower = type.toLowerCase();

  // Direct match
  if (BUSINESS_TYPE_PROFILES[lower]) return BUSINESS_TYPE_PROFILES[lower];

  // Partial match
  for (const [key, profile] of Object.entries(BUSINESS_TYPE_PROFILES)) {
    if (lower.includes(key) || key.includes(lower)) return profile;
  }

  // Trait-based fallback
  const traits = detectTraits(type);
  const bestChannels: string[] = ["go", "ig", "fb"];
  if (traits.visual) bestChannels.push("tt", "pi");
  if (traits.food) bestChannels.push("tt", "yp");
  if (traits.b2b) bestChannels.push("li");
  if (traits.entertainment) bestChannels.push("tt");
  if (traits.pets) bestChannels.push("tt");

  return {
    traits: Object.entries(traits).filter(([, v]) => v === true).map(([k]) => k),
    typicalCustomer: "Local customers in the area seeking quality service",
    visitFrequency: traits.food ? "weekly" : traits.service ? "quarterly" : "monthly",
    avgTransactionValue: traits.luxury ? 100 : traits.food ? 20 : traits.service ? 80 : 40,
    bestChannels: [...new Set(bestChannels)].slice(0, 5),
    contentTypes: ["customer experiences", "behind-the-scenes", "product/service showcases", "team highlights", "customer testimonials"],
    marketingStrengths: ["local presence", "customer relationships", "authentic content"],
    keyMetrics: ["new customers", "repeat rate", "review rating", "revenue growth"],
    membershipBased: false,
    seasonalPeaks: ["Holiday season", "New year", "Summer"],
  };
}
